### ISSUE TITLE
manpages

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#112]
Originally reported by: **Barry Warsaw (Bitbucket: [warsaw](https://bitbucket.org/warsaw), GitHub: [warsaw](https://github.com/warsaw))**

----------------------------------------

Three executable scripts are installed: wheel, egg2wheel, wininst2wheel.  These should have manpages.  I'll attach the rough and minimal ones I included in the Debian packaging for wheel.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/112

**Comment by agronholm** [comment]
@warsaw How do you propose that these man pages are installed by pip? Or do you just want us to put the files somewhere in the source tree?

**Comment by warsaw** [comment]
@agronholm Having them in the source tree would be enough for Debian.  Best would be to write them in reST and having them convertable via `rst2man`.

**Comment by agronholm** [comment]
Thanks for the man page. Hopefully someone will find time to improve it, as it is indeed pretty rough.
