### ISSUE TITLE
bdist_wheel needs an --exclude/-X option

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#113]
Originally reported by: **Barry Warsaw (Bitbucket: [warsaw](https://bitbucket.org/warsaw), GitHub: [warsaw](https://github.com/warsaw))**

----------------------------------------

I have to build lots of wheels to fix ensurepip (and thus pyvenv) for Python 3.4 in Debian.  I have to exclude certain directories from those wheels, such as requests/packages and pip/_vendor because including them will violate Debian policy.  In order to do this in the best way, I would like bdist_wheel to gain a --exclude option (and a short version probably too).

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/113

**Comment by agronholm** [comment]
@dholth Thoughts on this one? I'll happily implement this if the consensus is that it's the best way to handle such cases.

**Comment by dholth** [comment]
Fewnthoughts. Is it really a bug in what to include?El 6 ago. 2017 16:03, Alex Grönholm <notifications@github.com> escribió:@dholth Thoughts on this one? I'll happily implement this if the consensus is that it's the best way to handle such cases.

**Comment by agronholm** [comment]
I wonder if bdist_wheel is the right place to fix this. Is this useful outside of distro package building?

**Comment by agronholm** [comment]
I mean, Linux distributions often apply their own patches anyway. Would it not be just as convenient to remove the directories from the wheel after building it?

**Comment by dholth** [comment]
This would be a good use for the proposed 'wheel pack' command (compress a directory into a wheel, fixing up the manifest file)

**Comment by agronholm** [comment]
I feel that the new "wheel repack" command serves this use case well enough. Comment if you disagree.
