### ISSUE TITLE
Add a "default specific" platform tag option for pure Python wheels

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#153]
Originally reported by: **Nate Coraor (Bitbucket: [natefoo](https://bitbucket.org/natefoo), GitHub: [natefoo](https://github.com/natefoo))**

----------------------------------------

As detailed in issue #128 and issue #152, it's sometimes desirable to have a platform-specific platform tag even on pure Python wheels.  This is now possible with the `--plat-tag` option, but this requires the user to know what the correct tag is for the build platform. This information is easily acquired from `python setup.py bdist_wheel --help` or by calling `distutils.util.get_platform()`, but it'd be more convenient and less error-prone if there was a way to specify "I want the default platform-specific tag on this pure python wheel."

This could be done in a few different ways:

* A special reserved platform tag passed to `--plat-tag` like `default`, `arch_default`, `platform_default`, `platform`, etc.
* A new option such as `--nonpure-plat-tag`

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/153

**Comment by ncoghlan** [comment]
Perhaps `--plat-tag :default:`?

`pip` already uses the surrounding colon convention to denote special values like `--no-binary :all:` and `--only-binary :all:`.

**Comment by agronholm** [comment]
Closing as not relevant to this project anymore as `bdist_wheel` is now canonically part of setuptools.
