### ISSUE TITLE
bdist_wheel ccommand doesn't exist in Python 3

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#158]
Originally reported by: **Remco Haszing (Bitbucket: [remcohaszing](https://bitbucket.org/remcohaszing), GitHub: [remcohaszing](https://github.com/remcohaszing))**

----------------------------------------

When using Python 2.7, everything just works. However, when using Python 3.4 or Python 3.5, there doesn't seem to be a setuptools command `bdist_wheel`.
```
$ ./setup.py bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
$ pip list
pip (8.0.2)
setuptools (20.2.1)
wheel (0.29.0)
```

I've tried it both using a `pip install --user` installed environment and a virtualenv. This doesn't make a difference.

I used the same `setup.py` file for all situations.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/158

**Comment by nikolas** [comment]
I'm getting the invalid bdist_wheel error when after I've installed wheel:

```
~/src/django-global-context $ ./ve/bin/pip install wheel                                                                                   
Collecting wheel                                                                                                                           
  Using cached https://files.pythonhosted.org/packages/1b/d2/22cde5ea9af055f81814f9f2545f5ed8a053eb749c08d186b369959189a8/wheel-0.31.0-py2.py3-none-any.whl
Installing collected packages: wheel                                                                                                       
Successfully installed wheel-0.31.0                                                                                                        
(nik@maldive) :) (10:48)                                                                                                                   
~/src/django-global-context $ ./ve/bin/python setup.py sdist bdist_wheel                                                                   
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]                                                                      
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
(nik@maldive) :( 1 (10:48)                                                                                                                 
~/src/django-global-context $ ./ve/bin/python -c "import wheel"                                                                            
(nik@maldive) :) (10:48)                                                                                                                   
~/src/django-global-context $ 
```
Tried on Python 3.6.5rc1 and Python 2.7.14 with wheel 0.31.0.

**Comment by agronholm** [comment]
@nikolas I am unable to reproduce this. Can you give me precise instructions for reproducing the problem, starting from the creation of the virtualenv?

**Comment by pfmoore** [comment]
One thought - is your `setup.py` using setuptools? If it's using distutils alone, then there is no support in distutils for the wheel project to inject the `bdist_wheel` command, and you'd see the issue you describe. To use `bdist_wheel`, your project must use setuptools in its `setup.py`.

**Comment by nikolas** [comment]
Yeah, my issue was that, in my `setup.py`, `distutils` was getting imported instead of `setuptools`. Once I switched to `setuptools`, bdist_wheel worked fine.
