### ISSUE TITLE
Can wheels support configurable script installation locations?

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#162]
Originally reported by: **Leo Huckvale (Bitbucket: [lhuckvale](https://bitbucket.org/lhuckvale), GitHub: Unknown)**

----------------------------------------

It's not clear to me whether or not wheels will support configurable install locations for scripts. For eggs, this could be done with:

    python setup.py install --install-scripts=<target dir>

or via:

    pip install <pkg> --install-option=--install-scripts=<target dir>

Is this something which is currently (or could be) supported by wheels? As it stands, we have a [use case](https://github.com/pypa/pip/issues/2677#issuecomment-169746148) which requires configurable script installations, so we have to use eggs.

Is this functionality actually precluded by the wheel specification? If it is I'd like to know why, and would appreciate any advice to get around the issue. Otherwise, I'd appreciate it if someone could point me to the best place to contribute to a solution.

See related pip issue: [Determine what should be done about --(install|global)-option with Wheels #2677](https://github.com/pypa/pip/issues/2677)

Apologies if I have misused the "blocker" priority for this, but it is *literally* blocking me (and I would suspect not just me) from using wheels (and I would like to).

Many thanks,
Leo

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/162

**Comment by tuukkamustonen** [comment]
What is the real-world use case for this? https://github.com/pypa/pip/issues/2677#issuecomment-169746148 simply states that there is use case, but it doesn't what the use case actually is?

**Comment by agronholm** [comment]
This issue was originally a question and the answer seems to be "no".
