### ISSUE TITLE
Check wheel.pep425tags.get_supported() on Linux

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#170]
Originally reported by: **Daniel Holth (Bitbucket: [dholth](https://bitbucket.org/dholth), GitHub: [dholth](https://github.com/dholth))**

----------------------------------------

It looks like the tags can contain too many hyphens on Linux

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/170

**Comment by agronholm** [comment]
Every tuple in the list has 3 members and none of them have hyphens. So what is it that you mean?

**Comment by blikjeham** [comment]
It returns ('cp35', 'cp35m-x86_64-linux-gnu', 'linux_x86_64') on one of my systems. There seems to be an abundance of hyphens in the second member.

**Comment by agronholm** [comment]
@blikjeham could you elaborate on what kind of system produces that kind of a tuple?

**Comment by blikjeham** [comment]
@agronholm this is a CentOS 7 system running python 3.5 from the software collections. If you want more information on the system, I can provide the output of commands you want me to run.

**Comment by agronholm** [comment]
@blikjeham First of all, could you make sure you're trying this with the latest wheel release? Second, what does `distutils.get_platform()` give you?

**Comment by agronholm** [comment]
I tried this with the CentOS 7 Docker image and could not reproduce the problem, although I did only use the system default Python. I'll try to find the Python 3.5 package you mentioned.

**Comment by agronholm** [comment]
@blikjeham Installing Python 3.5 from software collections and running `get_supported()` from wheel 0.32, I still don't get any anomalous combinations so I have to close this issue as unreproduceable.
