### ISSUE TITLE
More flexibility about tags when shipping binaries

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#175]
Originally reported by: **Armin Ronacher (Bitbucket: [mitsuhiko](https://bitbucket.org/mitsuhiko), GitHub: [mitsuhiko](https://github.com/mitsuhiko))**

----------------------------------------

Currently there are a few situations that I would like to generate tags for but I can't.

In particular I have the following setups I care about:

* 2.x/3.x universal wheels that ship native extensions not linked against libpython and thus python version independent
* 2.x or 3.x specific wheels without abi identifier because not linking against libpython

This is from what I can tell not possible without monkey patching. Currently I'm doing this:

```
if bdist_wheel is not None:
    class CustomBdistWheel(bdist_wheel):
        def get_tag(self):
            rv = bdist_wheel.get_tag(self)
            return ('py2.py3', 'none') + rv[2:]
    cmdclass['bdist_wheel'] = CustomBdistWheel
```

I was thinking of sending a pull request but I'm not sure what the cleanest way to solve this is.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/175

**Comment by agronholm** [comment]
Looks like a duplicate of #161 yes?

**Comment by agronholm** [comment]
I feel this issue should be dealt with one way or another before the 1.0.0 release.

**Comment by ncoghlan** [comment]
Given the `--plat-tag` option, it seems like the natural extension would be to also offer `--abi-tag` and `--version-tag`.

All 3 could accept the `:default`: special value suggested in https://github.com/pypa/wheel/issues/153#issuecomment-406579300 to request the standard behaviour of inferring them from the running Python.

**Comment by ncoghlan** [comment]
(This could prove especially useful in combination with the new `wheel pack` command, since it opens the door to cross-compilation of wheel archives, where the currently running version of Python may have nothing to do with the version of Python being targeted)

**Comment by agronholm** [comment]
Closing as not relevant to this project anymore as `bdist_wheel` is now canonically part of setuptools. Also, `wheel tag` can be used to manipulate the tags as needed afterwards.
