### ISSUE TITLE
0.30.0a0 not in source control?

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#184]
Originally reported by: **reaperhulk (Bitbucket: [reaperhulk](https://bitbucket.org/reaperhulk), GitHub: [reaperhulk](https://github.com/reaperhulk))**

----------------------------------------

Is the source code in the sdist on PyPI for 0.30.0a0 present anywhere in the current hg tree? I've been unable to find it (no 0.30.0a0 tag and not present in the default branch).

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/184

**Comment by agronholm** [comment]
The latest source code should be in the repository.

**Comment by dholth** [comment]
There are a few extra commits in bitbucket.org/dholth/wheel including work to allow a separate build directory and some test improvements. And a commit adding 30a0.
