### ISSUE TITLE
Binary Wheels not linking against libpython

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#185]
Originally reported by: **Armin Ronacher (Bitbucket: [mitsuhiko](https://bitbucket.org/mitsuhiko), GitHub: [mitsuhiko](https://github.com/mitsuhiko))**

----------------------------------------

I'm currently using various different hacks that sometimes fail to create wheels with the following qualities:

* they are manylinux1 and mac wheels
* they use cffi to load shared libraries
* they do not link against libpython

Sadly they cannot be generated currently. The only way that sort of works is to put the shared libraries into the purelib root and it's not really purelib, is it.

Ideally there was a way to say: this wheel is py2.py3, has a manylinux/mac platform but no python abi.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/185

**Comment by agronholm** [comment]
@mitsuhiko Could you point me to a project I could use to verify that the issue is still relevant?

**Comment by agronholm** [comment]
Can we automatically somehow detect cases such as this?

**Comment by mitsuhiko** [comment]
@agronholm you can look at getsentry/symbolic which runs into this issue. We solved it by patching the hell out of bdist_wheel through our getsentry/milksnake library.

**Comment by agronholm** [comment]
Ok so let me just ask: what would you like me to change in wheel so I could close this issue?

**Comment by mitsuhiko** [comment]
@agronholm it needs a mode where you can define that your wheel contains binary data but is not linked against libpython. Effectively have something that lets me do what this does: https://github.com/getsentry/milksnake/blob/8351a8aa4ac800c586733602a55c1c02f0d19923/milksnake/setuptools_ext.py#L261-L278

**Comment by agronholm** [comment]
Hm, how about a `universal_binary` option (can anyone think of a better name?)? All it would do is add the architecture tag to the wheel. It would only take effect if no (traditional) C extensions are present.

I also thought about automatic detection of this condition but it would be too error prone.

**Comment by proppy** [comment]
@agronholm would that also work with app that bundle `.so` and load them with `ctypes`?

Currently, I'm bundle the `.so` as data and relying on @mitsuhiko [trick](http://lucumr.pocoo.org/2014/1/27/python-on-wheels/#building-wheels) to flag the wheel as not-pure.

But it doesn't trick auditwheel tool and it will continue to raise [` WheelToolsError('Cannot add platforms to pure wheel')`](https://github.com/pypa/auditwheel/blob/05afbdf81ad14687bd3abb469a1ecc127c5ccf0b/auditwheel/wheeltools.py#L191)

**Comment by mitsuhiko** [comment]
@proppy sadly there are limitations in distutils itself which means this flag can only be flagged by building a c extension. So what milksnake does not is building an empty C file and then later overrides the .so with the one from the milksnake build process.

**Comment by proppy** [comment]
@mitsuhiko is that something that could be patched up in `wheel` or does it have to be fixed in `distutils`?

**Comment by proppy** [comment]
@agronholm @mitsuhiko after looking at distutils source code and stealing a lot of milksnake awesome magic, I ended up the following workaround:
```
class UniversalBinaryDistribution(Distribution):
    def __init__(self, *args, **kwargs):
        super(UniversalBinaryDistribution, self).__init__(*args, **kwargs)
        base_bdist_wheel = self.cmdclass.get('bdist_wheel', bdist_wheel)
        class UniversalBdistWheel(base_bdist_wheel):
          def get_tag(self):
              rv = base_bdist_wheel.get_tag(self)
              return ('py2.py3', 'none',) + rv[2:]
        self.cmdclass['bdist_wheel'] = UniversalBdistWheel
        base_build_ext = self.cmdclass.get('build_ext', build_ext)
        class UniversalBuildExt(base_build_ext):
            def build_extension(self, ext):
                ext_filename = self.get_ext_filename(ext.name)
                shutil.copy2(ext_filename,
                             os.path.join(self.build_lib, ext_filename))
            def get_ext_filename(self, ext_name):
                ext_path = ext_name.split('.')
                ext_suffix = new_compiler().shared_lib_extension
                return os.path.join(*ext_path) + ext_suffix
        self.cmdclass['build_ext'] = UniversalBuildExt


setup(...
    ext_modules=[
        Extension('module.path.to..precompiledlib.without.so',
                  sources = [])
    ],
    distclass=UniversalBinaryDistribution,
)
```

It replaces the C compilation process with a `shutil.copy2` and the resulting wheels seems to pass auditwheel validation.

Is that something we could consolidate somewhere? (either in distutils or wheels)

**Comment by mitsuhiko** [comment]
One problem is that a lot of code just checks for `.extension_modules` or what that attribute is called. If it's empty it assumes pure eggs/wheels. There is a ton of code that just does that. All the workarounds I found break in fancy ways sadly. Even if auditwheel passes there is still embedded metadata which is kinda wrong.

**Comment by agronholm** [comment]
What metadata does that affect? IIRC wheel itself has the final say over the resulting wheel filename, so that's something I can fix here.

**Comment by proppy** [comment]
@agronholm the metadata that changed for me was: `Root-Is-Purelib: false` in `/WHEEL`

@mitsuhiko are you referring to the `ext_modules` parameter for the `setup()` call or `build_ext.extensions` internal variable?

**Comment by mitsuhiko** [comment]
The `extensions` parameter that is set on `build_ext` and others I think. I would need to look into it again though.

**Comment by agronholm** [comment]
Closing as not relevant to this project anymore as `bdist_wheel` is now canonically part of setuptools.
