### ISSUE TITLE
Wheel now depends on OrderedDict, not present in Python 2.6

### ISSUE THREAD

**Issue by matthew-brett** [pypa/wheel#193]
I guess this may be intended, but the new release of Wheel does not work with Python 2.6 unmodified, because it has:

```
from collections import OrderedDict
```

in "wheel/util.py", line 8 . I'm just flagging that in case it wasn't intended ...

https://travis-ci.org/matthew-brett/multibuild/jobs/274160483#L137

**Comment by pfmoore** [comment]
From the changelog

> Removed support for Python 2.6, 3.2 and 3.3.

So I guess this is intended.

**Comment by agronholm** [comment]
Indeed. Python 2.6 was EOL'd in October 29, 2013.
