### ISSUE TITLE
Remove or deprecate wheel signing features

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#196]
Signing wheels does not actually help a lot, as there is no infrastructure for distributing the authors' public keys. For this reason, I am in favor of getting rid of the signing features until such time that they can be replaced with something that provides real security benefits. Keeping `wheel sign` could be even dangerous as it may lull users into a false sense of security, thinking they or their users are better protected if they sign their wheels.

**Comment by westurner** [comment]
I disagree with the rationale for removing this feature.

I think that wheel signing should remain a part of this package; regardless of the lack of public key infrastructure.

**Comment by agronholm** [comment]
Why? In its present state it is **completely** useless.

**Comment by agronholm** [comment]
The current verification code trusts all keys implicitly.

**Comment by westurner** [comment]
Wheel signing prevents malicious use of #157 (e.g. automated repacking).

**Comment by westurner** [comment]
> The current verification code trusts all keys implicitly.

Do you have a link to this code?

**Comment by agronholm** [comment]
How does it prevent that?

**Comment by agronholm** [comment]
https://github.com/pypa/wheel/blob/master/wheel/signatures/__init__.py#L60

**Comment by westurner** [comment]
seeAlso:

"Implement "hook" support for package signature verification"
https://github.com/pypa/pip/issues/1035

- ... GPG is useless without a keyring and package author mappings
- TUF is the best solution

"The Update Framework (TUF)"
https://theupdateframework.github.io

-
Spec:  https://github.com/theupdateframework/specification/blob/master/tuf-spec.md
- Src: https://github.com/theupdateframework/tuf

**Comment by agronholm** [comment]
Yes, I am aware of TUF. What I am proposing is to drop the *current* implementation entirely and maybe later readd something when TUF becomes a reality.

**Comment by westurner** [comment]
From ``verify()`` in https://github.com/pypa/wheel/blob/master/wheel/signatures/__init__.py#L60 :
```
Caller must decide whether the keys are actually trusted
```

So, the signatures are useful; there's just no key checking?
Is there an example of deciding whether the keys are trusted? (... TUF has signing policies, etc)

**Comment by westurner** [comment]
> Why? In its present state it is completely useless.

Isn't it as useful

**Comment by agronholm** [comment]
The docstring is a bit odd, because there is no way to specify which keys are trusted. The signature is totally and completely pointless as such for combating malware.

> So, the signatures are useful; there's just no key checking?

Can you explain to me what the signatures are useful for?

**Comment by westurner** [comment]
The spec includes this feature. So, even though this verify() function is incomplete, it would be wrong to just remove it without also removing it from the spec.
 
- https://www.python.org/dev/peps/pep-0427/#signed-wheel-files
- https://www.python.org/dev/peps/pep-0491/#signed-wheel-files

I don't have the information needed to explain what completely implemented signatures are useful for. Does the spec explain this?

> A wheel installer is not required to understand digital signatures but MUST verify the hashes in RECORD against the extracted file contents. When the installer checks file hashes against RECORD, a separate signature checker only needs to establish that RECORD matches the signature.

**Comment by agronholm** [comment]
The idea behind the verification feature in the spec is useful when there is a proper key/trust management system in place. Right now there is none, nor is there any plan to implement such a thing. As it stands, the signing and verification feature is pointless and even potentially harmful, as it it not obvious that this is missing from the implementation.

**Comment by westurner** [comment]
On Sunday, October 29, 2017, Alex Grönholm <notifications@github.com> wrote:

> The idea behind the verification feature in the spec is useful when there
> is a proper key/trust management system in place. Right now there is none,
> nor is there any plan to implement such a thing. As it stands, the signing
> and verification feature is pointless and even potentially harmful, as it
> it not obvious that this is missing from the implementation.
>
So, rather than writing a function to check the key against a keyring,
you'd rather remove this security functionality from the spec and
implementation?

>

**Comment by ncoghlan** [comment]
The rationale for including this feature in the original specification was to secure build server -> deployment server links in environments where folks are doing the following:

- build server downloads source artifacts from PyPI (or elsewhere), creates wheel files, and publishes them to an internal repository
- deployments then rely solely on the internal repository, and don't require access to the public internet

This is essentially the way Linux distributions like Fedora use GPG signing - they're securing the link from the build environment to the final deployment, and hence can also take care of ensuring the deployment environment has access to the public key needed to check the signature.

So while there's not much point in uploading signed wheels to *PyPI* (just as there isn't much benefit from GPG signing artifacts published that way), the signing feature *does* help in managing private infrastructure for folks that either don't already have GPG infrastructure set up, or want to support Windows deployments without the hassle of getting GPG working reliably there.

**Comment by agronholm** [comment]
Well, I don't see the verification, in its current state, doing anything in private use either.

**Comment by agronholm** [comment]
> So, rather than writing a function to check the key against a keyring,
you'd rather remove this security functionality from the spec and
implementation?

It depends on whether the verification functionality is deemed useful with a keyring, or if another approach is considered better. I would like input from multiple perspectives on this matter before proceeding to do anything.

**Comment by ncoghlan** [comment]
In that case I'll defer to @dholth, as the conceptual design as a build server -> target system integrity measure still seems sound to me (so I don't see a compelling reason to remove it from the specification), but if the current reference implementation isn't providing the intended security guarantees, I agree it would qualify as a problematic attractive nuisance (similar to CPython's historical failure to properly validate HTTPS certificates).

**Comment by dholth** [comment]
The idea was that you could share references to public keys in exactly
the same way that you might specify hashes today. Perhaps a trust-on-first-
use scheme could have been developed. Unfortunately I was trying to
promote non-NIST cryptography before the Snowden leaks and wasn't able
to build a shared vision with the mailing list.
Certainly no one is accidentally getting a false sense of security from
the feature.
On Mon, Oct 30, 2017, at 03:19 AM, Nick Coghlan wrote:
> In that case I'll defer to @dholth[1], as the conceptual design as a
> build server -> target system integrity measure still seems sound to
> me (so I don't see a compelling reason to remove it from the
> specification), but if the current reference implementation isn't
> providing the intended security guarantees, I agree it would qualify
> as a problematic attractive nuisance (similar to CPython's historical
> failure to properly validate HTTPS certificates).> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/dholth
  2. https://github.com/pypa/wheel/issues/196#issuecomment-340362106

**Comment by agronholm** [comment]
I think it boils down to two options:

1. We add some kind of mechanism for the user to tell `wheel` what keys to trust
2. We remove the verification mechanisms entirely, perhaps even the signing part

The first option would only be useful if `wheel` was being used to install wheels. As it is not, there is pretty much no point in going through the trouble. Keeping the wheel signing functionality would make sense if another, widely used tool (read: `pip`) had at least plans for implementing a trust model for these signatures. Does it?

> Certainly no one is accidentally getting a false sense of security from
the feature.

I at least was under the impression that wheel signing was a useful feature, prior to taking up maintainership.

**Comment by dholth** [comment]
I do like the feature and especially think it's valuable to be able to sign the contents with a bundled signature independent of the compression. It would take a sponsor to further develop the feature into something more people would use. I don't think anyone would accidentally think the signature means more than it actually does, independent of how many people might use the feature.On Oct 30, 2017 18:35, Alex Grönholm <notifications@github.com> wrote:I think it boils down to two options:
We add some kind of mechanism for the user to tell wheel what keys to trustWe remove the verification mechanisms entirely, perhaps even the signing part
The first option would only be useful if wheel was being used to install wheels. As it is not, there is pretty much no point in going through the trouble. Keeping the wheel signing functionality would make sense if another, widely used tool (read: pip) had at least plans for implementing a trust model for these signatures. Does it?

Certainly no one is accidentally getting a false sense of security from
the feature.

I at least was under the impression that wheel signing was a useful feature, prior to taking up maintainership.

**Comment by ncoghlan** [comment]
Keeping only the `RECORD` signing as a publicly supported feature, while treating the question of signature verification purely as a self-test concern would make sense to me, since wheel's native installation capabilities in general are just for self-test purposes.

I confess I don't have a solid user-driven rationale for that preference though - I just like the notion of the wheel format offering a Windows-friendly (i.e. not GPG-based) transport-independent mechanism for content validation if folks want to use it (even if actually using it requires devising an out-of-band mechanism to manage the key distribution + signature verification problem).

That said, I'll also note that the essential mechanism in the wheel specification that enables embedded signatures is just the permission to include a `RECORD.jws` or `RECORD.p7s` file without listing it in `RECORD`. Other unlisted files will cause installation with a standards compliant installer to fail due to PEP 427's "Apart from RECORD and its signatures, installation will fail if any file in the archive is not both mentioned and correctly hashed in RECORD" requirement.

That means that even if wheel itself were to drop native support for signature generation, then signature files could still be injected into the archive post-build.

So I think it ultimately comes down to how much of a pain Alex thinks it will be to maintain the native signing feature and its self-tests, and what we think the odds might be of anyone investing time in further enhancing a Python-specific build integrity assurance mechanism (vs ensuring the integrity of wrapper formats like conda, Linux system packages, Windows installers, container images, machine images, etc).

**Comment by agronholm** [comment]
It sounds to me like this warrants further discussion on distutils-sig.
