### ISSUE TITLE
Implementation of ABI tags not well-defined

### ISSUE THREAD

**Issue by vsajip** [pypa/wheel#202]
The exact value of ABI tags seems to be not well-defined in PEP 427 / PEP 491. It is derived from the `sysconfig` variable `SOABI`, but the exact derivation from that seems implementation-dependent. The [current implementation](https://github.com/pypa/wheel/blob/master/wheel/pep425tags.py#L90) takes a `SOABI` value such as `cpython-35m-darwin` and converts it to `cp35m`, dropping the `-darwin`, but presumably this has a meaning which shouldn't be lost. What's the rationale for this particular way of deriving the tag, rather than say converting to `cp35m-darwin` which doesn't lose information about the underlying Python ABI?

**Comment by agronholm** [comment]
I'm not entirely sure if this is the right place to post this issue. It seems more like a standards problem and not an implementation one. If I'm wrong, what do you expect me to do about it?

**Comment by agronholm** [comment]
@vsajip Care to comment? If not, I have to close this issue.

**Comment by vsajip** [comment]
> It seems more like a standards problem and not an implementation one

I agree that the specification is not well-defined, but it might be useful if we can agree a common implementation while there remains this ambiguity. As I see it, the wheel implementation strips some potentially useful information from the underlying ABI tag as provided by CPython, for no good reason that I can see. So my question above:

> What's the rationale for this particular way of deriving the tag, rather than say converting to cp35m-darwin which doesn't lose information about the underlying Python ABI?

relates to the specific implementation in wheel, and it would be nice to have an answer for it.

**Comment by dholth** [comment]
Interestingly wheel 0.24's get_supported() includes cp35m-darwin as the ABI tag. Don't know when this changed.

**Comment by agronholm** [comment]
I'm closing this issue until someone can come up with practical steps that will not prevent the resulting wheels from being installed with pip (as I suspect that the suggested tags would do). Otherwise this will become one of those tickets that linger for years.
