### ISSUE TITLE
bdist_wheel being run instead of install, advice needed

### ISSUE THREAD

**Issue by AndrewAnnex** [pypa/wheel#204]
Hey so in my setup.py https://github.com/AndrewAnnex/SpiceyPy/blob/master/setup.py, I implement the `install` command for my package as I need to build and bundle a shared library which I do at "build time" aka the run time of my setup.py. 

I noticed that on my mac if I run `pip install spiceypy` to install from pypi I notice that pip attempts to build a wheel instead of running my install command (I see "Running setup.py bdist_wheel for spiceypy" in the terminal). Because this side steps the Install command it does hit my code which builds the shared library. If I instead install using --no-cache-dir that appears to trigger the correct behavior (the Install command is executed instead). 

Could I get a recommendation for a fix?  should I update the cmdclass to include an override for bdist_wheel? I had not found any documentation that clearly explained the interactions between pip, setuptools, and wheel so any blog posts/ links to sections in docs would be appreciated. 

Thanks

**Comment by hsiaoyi0504** [comment]
@AndrewAnnex Can you share your solution of this ?

**Comment by AndrewAnnex** [comment]
@hsiaoyi0504 I fixed it by overriding build_py, but this issue might be solved using the manifests.in which I thought I had tried but have not gone back to check on, specific changes: https://github.com/AndrewAnnex/SpiceyPy/commit/7e4fcb9a32d1fbd2e0051ed0e5ca115e2ca1843e

**Comment by hsiaoyi0504** [comment]
@AndrewAnnex Thanks for sharing that. I also got it work later at that day, but I and not sure if I do it correct or not. Based on description here: https://pip.pypa.io/en/stable/reference/pip_install/#id21, pip install will always try to build wheel first. Therefore, I need to do something like this: https://github.com/NAL-i5K/GFF3toolkit/blob/ca4e0506b30fafa04354f1e17b3597947ea7945e/setup.py#L19-L30 to force it to run the build each time.
