### ISSUE TITLE
egg2dist solicits distinfo_path from two places

### ISSUE THREAD

**Issue by jaraco** [pypa/wheel#206]
Discovered in pypa/setuptools#1196, it seems that the egg2dist function both accepts a parameter distinfo_path but also accesses self.distinfo_dir. When egg2dist is invoked from an external caller like setuptools, and distinfo_dir isn't set, and the license text functionality is triggered, the function will crash with a TypeError.

egg2dist should either only use distinfo_path passed as a parameter or use the instance attribute. Even better, if possible, egg2dist should be refactored such that it doesn't depend on instance attributes at all (and thus can be a classmethod).

**Comment by agronholm** [comment]
It should be noted that wheel does **not** have a public API. If you import wheel code directly, it may break in the next release.

**Comment by agronholm** [comment]
I'll get this fixed for the next release, if possible. I'm doing a rather large refactoring of the code base now.
