### ISSUE TITLE
Wheel crashes with UTF-8 filenames

### ISSUE THREAD

**Issue by julienmalard** [pypa/wheel#207]
**Wheel does not work when the project contains utf-8 filenames.

Sample traceback:**

C:\Users\jmalar1\PycharmProjects\Tikon>python setup.py bdist_wheel

running bdist_wheel
running build
running build_py
installing to build\bdist.win32\wheel
running install
running install_lib
running install_egg_info
running egg_info
writing tikon.egg-info\PKG-INFO
writing dependency_links to tikon.egg-info\dependency_links.txt
writing top-level names to tikon.egg-info\top_level.txt
reading manifest file 'tikon.egg-info\SOURCES.txt'
writing manifest file 'tikon.egg-info\SOURCES.txt'
Copying tikon.egg-info to build\bdist.win32\wheel\.\tikon-1.1.0-py3.6.egg-info
running install_scripts
creating build\bdist.win32\wheel\tikon-1.1.0.dist-info\WHEEL
Traceback (most recent call last):
  File "setup.py", line 289, in <module>
    '': ['*.csv', 'versión.txt', '*.json', 'Interfaz/*.png', 'Interfaz/*.jpg'],
  File "C:\Users\jmalar1\AppData\Local\Programs\Python\Python36-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\jmalar1\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\jmalar1\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\jmalar1\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wheel\bdist_wheel.py", line 261, in run
    self.write_record(self.bdist_dir, self.distinfo_dir)
  File "C:\Users\jmalar1\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wheel\bdist_wheel.py", line 482, in write_record
    writer.writerow((record_path, hash, size))
  File "C:\Users\jmalar1\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 15-23: character maps to <undefined>

**Comment by agronholm** [comment]
I tried adding wheel/tool/åäö.py and building the wheel and it worked fine. So UTF-8 is not the problem here. As you can see from your own traceback, it tries to encode the file name in cp-1252, not UTF-8. Why it tries to do that in the first place is the real question.

**Comment by agronholm** [comment]
@julienmalard Are you by any chance using Conda?

**Comment by julienmalard** [comment]
Hello,


No, I am using a regular installation of Python 3.6 However, I had omited to mention that the problem occurs when I have folder (sub-package) names in a different script. Could that be the problem?


Many thanks for the help!

-Julien Malard

________________________________
દ્વારા: Alex Grönholm <notifications@github.com>
મોકલ્યું: 03 જાન્યુઆરી 2018 16:08:07
પ્રતિ: pypa/wheel
Cc: Julien Malard; Mention
વિષય: Re: [pypa/wheel] Wheel crashes with UTF-8 filenames (#207)


@julienmalard<https://github.com/julienmalard> Are you by any chance using Conda?

**Comment by julienmalard** [comment]
Hello,

No problem! The Tiko'n repository (https://github.com/julienmalard/Tikon) still runs into this error.

**Comment by agronholm** [comment]
Seems like a Windows only problem, as I cannot reproduce this on Linux. I'll try on Windows next.

**Comment by julienmalard** [comment]
I'm using Windows 7 (64-bit) with a 32-bit version of Python 3.6.2.

Many thanks!


________________________________
દ્વારા: Alex Grönholm <notifications@github.com>
મોકલ્યું: 30 માર્ચ 2018 06:54:40
પ્રતિ: pypa/wheel
Cc: Julien Malard; Mention
વિષય: Re: [pypa/wheel] Wheel crashes with UTF-8 filenames (#207)


Seems like a Windows only problem, as I cannot reproduce this on Linux. I'll try on Windows next.

**Comment by agronholm** [comment]
@julienmalard I was able to reproduce the problem on Windows.

I have to say, that setup.py is pretty bad. Why do I have to install numpy and upgrade pip just to make a wheel? Never before have I encountered a setup.py as invasive as this one. I'll also point out that it's bad practice to have variables, modules or other code in a natural language other than English. Not that it excuses wheel tripping on unicode filenames, but still.

**Comment by julienmalard** [comment]
Hello,


Thank you; that is very nice to hear!


Apologies for the setup.py file. It was my beginner's attempt to make it install automatically on Windows without manual installation of numpy binaries; I found a much better solution since by offering a separate "preinstall.py" file for Windows users (I have fixed it in my other main repository<https://github.com/julienmalard/Tinamit> and should have ported it to Tiko'n as well long before now!)


As for languages, we are developing this for a mainly non-English audience, and want other cultures to be able to fully participate in development (we also have a repository in Urdu<https://github.com/julienmalard/Taqdir/tree/master/taqdir> from a climate change project in Pakistan!). I do agree that with English-language Python keywords, it is a bit odd, but so far this is the only option officially supported<https://www.python.org/dev/peps/pep-3131/>. One interest of mine (after I graduate!) would be to develop a SASS or Typescript-like software that allows developers to develop entirely in one natural language (including keywords) and then compile to original Python keywords before execution. Would be happy to hear your thoughts!


Anyways, please let me know if I should provide anything else to help fix the bug. I will also push a more respectable setup.py soon.


Much appreciate your support!

-Julien

________________________________
દ્વારા: Alex Grönholm <notifications@github.com>
મોકલ્યું: 31 માર્ચ 2018 10:20:36
પ્રતિ: pypa/wheel
Cc: Julien Malard; Mention
વિષય: Re: [pypa/wheel] Wheel crashes with UTF-8 filenames (#207)


@julienmalard<https://github.com/julienmalard> I was able to reproduce the problem on Windows.

I have to say, that setup.py is pretty bad. Why do I have to install numpy and upgrade pip just to make a wheel? Never before have I encountered a setup.py as invasive as this one. I'll also point out that it's bad practice to have variables, modules or other code in a natural language other than English. Not that it excuses wheel tripping on unicode filenames, but still.

**Comment by agronholm** [comment]
While investigating this I found another bug which, on Python 2, would cause non-ASCII file names to be encoded using the local preferred encoding instead of UTF-8. The commit referenced above fixes both problems.

**Comment by julienmalard** [comment]
Many thanks!

________________________________
દ્વારા: Alex Grönholm <notifications@github.com>
મોકલ્યું: 31 માર્ચ 2018 13:56:37
પ્રતિ: pypa/wheel
Cc: Julien Malard; Mention
વિષય: Re: [pypa/wheel] Wheel crashes with UTF-8 filenames (#207)


While investigating this I found another bug which, on Python 2, would cause non-ASCII file names to be encoded using the local preferred encoding instead of UTF-8. The commit referenced above fixes both problems.
