### ISSUE TITLE
wheel as optional package

### ISSUE THREAD

**Issue by dvarrazzo** [pypa/wheel#215]
Hello,

I'm currently packaging [psycopg2 as wheel](https://github.com/psycopg/psycopg2-wheels/) but the package has problems because the depending libraries include `libssl`, which can conflict with the system libssl, e.g. used by `urllib` (see psycopg/psycopg2#543). Unfortunately libssl doesn't have a standard ABI, so I don't think the situation can be solved.

Wheels have made life easier for a lot of people, allowing people to install the package without its build and runtime requirements, but because the resulting package is not reliable, and unfortunately it shows unreliability in situations easier to meet in production than in development/testing (it is a concurrency problem) it cannot be the default installation method.

I would like to make the wheel optional, i.e. `pip install psycopg2` should attempt to install the package from source, and in order to get the wheel some command line switch should be used, e.g. `pip install --binary psycopg2`. Is there any provision for this?

Alternatively I'm planning to release a separate package, `psycopg2-binary` and propose its installation in the `setup.py` if the build prerequisites are not met. Is this my only/best option?

Thank you.

**Comment by dvarrazzo** [comment]
My current plan is to release a `psycopg2-binary` package containing the wheel, and leave the source only as `psycopg2`. Further info in [this ML message](https://www.postgresql.org/message-id/CA%2Bmi_8bd6kJHLTGkuyHSnqcgDrJ1uHgQWvXCKQFD3tPQBUa2Bw%40mail.gmail.com). Feedback is welcome.

**Comment by agronholm** [comment]
Pip can be told to install distributions from source and ignore wheels, on a distribution level if necessary. Would it be a problem to link libssl statically?

**Comment by DanielShaulov** [comment]
FYI, now that pypa/pip#3785 is fixed, this can be somewhat achieved by making sure that the source is always a higher version than the wheel (x.y.z for wheel and x.y.z.post1 for the source for example). Then the default is the source, but if someone sets the `--prefer-binary` flag he will get the wheel.

**Comment by agronholm** [comment]
I don't think there's anything I can do here, so I'm closing this.
