### ISSUE TITLE
Allow large archives

### ISSUE THREAD

**Issue by samikama** [pypa/wheel#221]
Hello,

Would it be possible to add large file support? For some debug archives zip file limit is exceeded and zipfile throws a
'
 zipfile.LargeZipFile: Filesize would require ZIP64 extensions
'
It should be a few lines of change if not one.

Thanks,
Sami

**Comment by george-peng-git** [comment]
I have the same issue.
Related discussion here: https://github.com/tensorflow/tensorflow/issues/5538

**Comment by mvsusp** [comment]
I have the same issue as well.

**Comment by agronholm** [comment]
@mvsusp You did notice that the issue was closed with a commit, right?

**Comment by mvsusp** [comment]
@agrnholm, I actually didn’t! Thanks for the heads up and fast response.

**Comment by JaviMerino** [comment]
The commit does not fix the issue, if you look at the traceback in tensorflow/tensorflow#5538 , the issue is on wheel/archive.py .  Pull request #233 fixes this issue for me.

**Comment by agronholm** [comment]
You're right, the commit only fixes the issue for some functionality in wheel, but not the archiving part.
