### ISSUE TITLE
dependency_links in setup.py not being reflected in wheel installation

### ISSUE THREAD

**Issue by trianta2** [pypa/wheel#225]
If a setup.py uses `setup(dependency_links=[...])`, and a wheel is made from that project, I have found that the dependency specified will not be resolvable when you try to pip install the resulting wheel. Creating source distributions works as expected however.

For example if `python setup.py bdist_wheel` produces `dist/my-pkg.whl`, then `pip install my_pkg --process-dependency-links --find-links dist/` will fail.

However if I did `python setup.py sdist` then `pip install my_pkg --process-dependency-links --find-links dist/` would work.

**Comment by agronholm** [comment]
`dependency_links` has no corresponding packaging metadata, nor will there be any as I understand. I suggest you use the `-f` option for pip or set up a private repository (using devpi).
