### ISSUE TITLE
Produce a compatible wheel from Cygwin

### ISSUE THREAD

**Issue by giampaolo** [pypa/wheel#226]
Hello. I have a Python C extension module including different `Makefile`s which I can successfully compile on Windows via cygwin / msys. I am able to produce a wheel like this:

```
tp-0.1.4+297.gf42c2c8-cp36-cp36m-mingw64_nt_10_0_2_9_0_x86_64.whl
```

I then need to pip-install this wheel from "plain" (non cygwin) system Python, aka `C:\python36-64\python.exe` [1] but the above wheel is not compatible:

```
tp-0.1.4+297.gf42c2c8-cp36-cp36m-mingw64_nt_10_0_2_9_0_x86_64.whl is not a supported wheel on this platform
```

Is there anything I can do?

[1] this is a requirement because pyinstaller doesn't work with cygwin

**Comment by agronholm** [comment]
I'm afraid this cannot work, as extension modules need to be compiled with the same compiler as Python itself. If memory serves, Visual Studio 2015 is required.
