### ISSUE TITLE
WheelFile does not properly close the underline file descriptor

### ISSUE THREAD

**Issue by marcogiusti** [pypa/wheel#227]
`WheelFile` could open a file descriptor the first time the `zipfile` attribute is accessed. That file descriptor is never closed, especially when the verification fails.

https://github.com/pypa/wheel/blob/master/wheel/install.py#L231

**Comment by agronholm** [comment]
Obsoleted by refactoring done in 89492505b968f6bf9ae9cc35f88f8ecd6ce6cbf1.
