### ISSUE TITLE
RECORD file generation should be idempotent 

### ISSUE THREAD

**Issue by af6140** [pypa/wheel#229]
The generated RECORD file entries order may vary between runs. This causes problem when deploying aws lambda package, since the checksum changes.

**Comment by agronholm** [comment]
I find this odd given that directories and file names are sorted while walking the directory tree. Can you consistently reproduce this problem?

**Comment by agronholm** [comment]
@af6140 I will fix this by the end of the week if you have time to work with me on this. Otherwise I will move this to the next release.

**Comment by agronholm** [comment]
I'm still willing to fix this but it'll have to wait until the next release.

**Comment by af6140** [comment]
Was out of town, ok to fix in next release.

**Comment by agronholm** [comment]
But I still have no idea how to reproduce the problem. Please provide instructions.

**Comment by agronholm** [comment]
Cannot reproduce and OP has not responded in 5 weeks so I'm closing this. Comment if you feel this is wrong.

**Comment by dholth** [comment]
Possibly they are using an old version.
