### ISSUE TITLE
WHEEL_INFO_RE no longer accepts name

### ISSUE THREAD

**Issue by terrelln** [pypa/wheel#236]
Since commit 88c480e7679700b43810cd6020fef9104bef6237 `WHEEL_INFO_RE("package-0.1.dist-info") == None`.

If this is expected, sorry for the noise.

**Comment by jamadden** [comment]
This looks like #235 which was closed as invalid:

> As wheel does not have a public API, the developers are not responsible for any breakage caused by internal refactoring. I suggest that you copy the regex to your own app.

**Comment by terrelln** [comment]
That makes sense, but maybe the `.dist-info` part of the regex could be completely removed, since it no longer works.
