### ISSUE TITLE
Inconsistency between bdist_wheel and rotate with underscores/hyphens

### ISSUE THREAD

**Issue by ThimoNeubauer** [pypa/wheel#238]
I fear that this might be closed as "not a bug" either for the wheel or the setuptools package. Anyway, I've stumbled over the effect and would like to at least leave something to find for anybody also experiencing the effect.

Unzip [inconsistency.zip](https://github.com/pypa/wheel/files/2083904/inconsistency.zip) to get a dummy setup where the key part in setup.py is:

    setup(
      name="foo-bar",
      ...
    )

When executing `setup.py bdist_wheel` I get a file called `foo_bar-1-py3-none-any.whl` (with an underscore).

However when running `setup.py rotate --match .whl --keep 0` to throw away previous wheel builds it won't work. The reason is pretty obvious because the screen output says:

    running rotate
    running egg_info
    writing foo_bar.egg-info\PKG-INFO
    writing dependency_links to foo_bar.egg-info\dependency_links.txt
    writing top-level names to foo_bar.egg-info\top_level.txt
    reading manifest file 'foo_bar.egg-info\SOURCES.txt'
    writing manifest file 'foo_bar.egg-info\SOURCES.txt'
    0 file(s) matching foo-bar*.whl

Note the `foo-bar*.whl` in the last line...

The behavior of rotate is consistent with the names of what `setup.py sdist` creates, thus I concluded that it would rather be a problem of wheel than of setuptools.

I have setuptools version 39.2.0 and wheel version 0.31.1 installed.

**Comment by agronholm** [comment]
None of this touches wheel code, unless you feel that wheel is wrong to replace the `-` with a `_` (as it should according to the wheel spec ([PEP 427](https://www.python.org/dev/peps/pep-0427/#id12).
