### ISSUE TITLE
Failure to include extension modules when ~/.pydistutils.cfg sets `[build_ext] inplace = true`

### ISSUE THREAD

**Issue by anntzer** [pypa/wheel#241]
I have a ~/.pydistutils.cfg (https://docs.python.org/3/install/index.html#location-and-names-of-config-files) with the following contents:
```
[build_ext]
force = true
inplace = true
```
(essentially allowing me to type `python setup.py build_ext` instead of `python setup.py build_ext --force --inplace`; the former because I use ccache to cache my compilations anyways and many packages don't declare source dependencies properly (causing distutils's timestamp scheme to fail) and the latter because I have a lot of editable-installed, with-extension packages.)

When the `inplace = true` line is added, trying to build a wheel for e.g. numpy, pandas, or various other common scientific python packages from a source checkout (`python setup.py bdist_wheel`) fails to include the `.so` files in the wheel (thus generating an incorrect wheel).  Removing the `inplace = true` line fixes the issue.  (Unfortunately, I was not able to reproduce the issue using smaller, minimal examples.)

I'm not exactly sure what the underlying issue is, but I'd guess that when `wheel` is invoking `build_ext`, it should make sure that `--inplace` is not set (asusming that that's indeed the problem)?

**Comment by anntzer** [comment]
You can probably test using a local setup.cfg (item (3) of https://docs.python.org/3/install/index.html#location-and-names-of-config-files), which will likely cause the same issue?

**Comment by agronholm** [comment]
You said yourself that you were unable to reproduce the issue using smaller, minimal examples. So what gives?

**Comment by anntzer** [comment]
Oh sorry I forgot about that.  Let me give it a try again.

**Comment by anntzer** [comment]
Actually it wasn't too hard to figure it out: numpy.distutils must also be involved to reproduce the failure (so I guess numpy.distutils is possibly the one at fault...).

setup.py:
```
import setuptools
from numpy.distutils.core import setup, Extension
setup(name="foo",
      ext_modules=[Extension("foo", ["foo.c"])])
```
setup.cfg:
```
[build_ext]
inplace = true
```
foo.c:
```
#include "Python.h"
PyObject* PyInit_foo(void) { return NULL; }
```

Running `python setup.py bdist_wheel` results in a wheel without the extension included.

**Comment by agronholm** [comment]
I was unable to reproduce the problem with these instructions. This is what I ended up with:
```
Archive:  dist/foo-0.0.0-cp37-cp37m-linux_x86_64.whl
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
   36920  Defl:N    12132  67% 12-10-2018 10:13 5d0068a1  foo.cpython-37m-x86_64-linux-gnu.so
     167  Defl:N      105  37% 12-10-2018 10:13 1cb9c828  foo-0.0.0.dist-info/METADATA
     104  Defl:N      101   3% 12-10-2018 10:13 8add7d16  foo-0.0.0.dist-info/WHEEL
       4  Defl:N        6 -50% 12-10-2018 10:13 7e3265a8  foo-0.0.0.dist-info/top_level.txt
     374  Defl:N      265  29% 12-10-2018 10:13 f45db405  foo-0.0.0.dist-info/RECORD
--------          -------  ---                            -------
   37569            12609  66%                            5 files
```
I used Python 3.7 with numpy==1.15.4. Do I need specific versions of both as well?

**Comment by anntzer** [comment]
I am using the same versions as you.

I can also confirm the same issue using a clean python:3.7.0-slim-stretch docker image (`pip install numpy==1.15.4 && apt update && apt install gcc` and create the files with the contents above).

**Comment by agronholm** [comment]
The fault was mine; I was running it against an attempted fix version.
Please try again with this branch: https://github.com/pypa/wheel/tree/inplace
Let me know if it works for you.

**Comment by anntzer** [comment]
Indeed, it does.
Thanks!

**Comment by anntzer** [comment]
Is this ready for merge?

**Comment by agronholm** [comment]
Damn, I had totally forgotten about this. I'll go merge it now.

**Comment by agronholm** [comment]
Yep, I'm retarded. This is already in 0.33.0 but since I forgot about it, it's not mentioned in the changelog.

**Comment by anntzer** [comment]
Thanks!
