### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by hroncok** [pypa/wheel#254]
Hello. We would really like d3f5918ccbb1c79e2fc42b7766626a0aa20dc438 in Fedora. Is there a timeframe for the new release?

Thanks

cc @stratakis

**Comment by benoit-pierre** [comment]
See https://github.com/pypa/wheel/pull/250#issuecomment-423913405.

**Comment by hroncok** [comment]
Thanks for the quick answer.

**Comment by agronholm** [comment]
I just released v0.32.0.
