### ISSUE TITLE
RECORD file has zero permissions after wheel 0.32.0

### ISSUE THREAD

**Issue by anthrotype** [pypa/wheel#261]
opening a separate ticket from https://github.com/pypa/wheel/issues/255#issuecomment-426170010

@safiyat wrote:

> I am able to reproduce the zero-permissions RECORD file problem as faced by @matthew-brett.
> Pardon my use of unzip, but after unzipping the wheel, I see that the RECORD file has the permission bits set to 000. The output of ls -l listed below for your perusal.

```
total 44
-rw-rw---- 1 jenkins jenkins  2692 Oct  2 06:01 METADATA
---------- 1 jenkins jenkins 27811 Oct  2 06:01 RECORD
-rw-rw---- 1 jenkins jenkins    82 Oct  2 06:01 WHEEL
-rw-rw---- 1 jenkins jenkins    57 Oct  2 06:01 entry_points.txt
-rw-rw---- 1 jenkins jenkins    17 Oct  2 06:01 top_level.txt
```

> I am using wheel 0.32.0 and Python 2.7.6.

**Comment by agronholm** [comment]
I have a fix ready which I will test later today. when that is done I will make a new patch release.

**Comment by anthrotype** [comment]
Thank you very much!

**Comment by agronholm** [comment]
What are the expected permissions on the files in a wheel? From my quick check, this seems to depend on the current umask.

**Comment by agronholm** [comment]
I'm not sure what permissions to set on the file. I'd prefer setting 0o644 but I need confirmation from other developers before proceeding.

**Comment by dholth** [comment]
Do that but preserve the execute bit especially for scripts.

**Comment by safiyat** [comment]
@agronholm I compared the permissions of the files created by wheel 0.31.1 and 0.32.0.

All the permissions are the same. The executable scripts have the executable bit set. The problem is only with the `RECORD` file. Its permission in 0.32.0 are `000`, while in 0.31.1 the permission bits are `644`.

**Comment by benoit-pierre** [comment]
I think the current umask should be respected:
```diff
 wheel/wheelfile.py | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git i/wheel/wheelfile.py w/wheel/wheelfile.py
index 9eea0aa..a584b0d 100644
--- i/wheel/wheelfile.py
+++ w/wheel/wheelfile.py
@@ -25,6 +25,11 @@ def get_zipinfo_datetime(timestamp=None):
     timestamp = int(os.environ.get('SOURCE_DATE_EPOCH', timestamp or time.time()))
     return time.gmtime(timestamp)[0:6]
 
+def get_current_umask():
+    umask = os.umask(0)
+    os.umask(umask)
+    return umask
+
 
 class WheelFile(ZipFile):
     """A ZipFile derivative class that also reads SHA-256 hashes from
@@ -154,6 +159,7 @@ def close(self):
             content += '\n{},,\n'.format(self.record_path)
             zinfo = ZipInfo(native(self.record_path), date_time=get_zipinfo_datetime())
             zinfo.compress_type = ZIP_DEFLATED
+            zinfo.external_attr = (0o666 & ~get_current_umask()) << 16
             self.writestr(zinfo, as_bytes(content))
 
         super(WheelFile, self).close()
```

**Comment by safiyat** [comment]
> That's because the new code is not setting the external attributes when creating the zip entry for RECORD (previously a temporary file would be created, and those attributes would be set from it).

That may be, but I think there should be consistency among all the files in the dist-info directory.

> Note that I can only reproduce the bug with Python 2, or at least not with Python 3.7.

I am not sure if the support for Python <= 2.7.6 should be rescinded. I leave it up to you.

**Comment by benoit-pierre** [comment]
> > That's because the new code is not setting the external attributes when creating the zip entry for RECORD (previously a temporary file would be created, and those attributes would be set from it).
> 
> That may be, but I think there should be consistency among all the files in the dist-info directory.

Yes, that's what my patch above does.

**Comment by benoit-pierre** [comment]
And I'm pretty sure @agronholm does not intend on dropping Python 2.7 support :P.

**Comment by agronholm** [comment]
> I think the current umask should be respected:

Why do you think that? On Windows, all the resulting wheel files have a mode of 0o666.
Any sane installer will override the permissions in the wheel file anyway.

**Comment by benoit-pierre** [comment]
Does that mean that an installer should completely ignore permissions? Automatically setting execute rights for scripts / directories on Unix. It's too bad [PEP 427](https://www.python.org/dev/peps/pep-0427/) does not say anything about the subject.

**Comment by benoit-pierre** [comment]
If that's the case, what's the issue? A wheel with a zero permissions RECORD entry is perfectly valid.

**Comment by safiyat** [comment]
Thanks!
