### ISSUE TITLE
bdist_wheel failing with setuptools with bad wheel name

### ISSUE THREAD

**Issue by OmSaran** [pypa/wheel#265]
`python setup.py bdist_wheel` uses **bdist_wheel.py** from wheel package. Since version 0.32.0 it no longer works with version names that does not match https://github.com/pypa/wheel/blob/master/wheel/wheelfile.py#L16:L19

Version names not matching the above regex did not fail with older versions of wheel.
Also **PEP 427** does not enforce using **PEP 440** standard version names.

**Comment by benoit-pierre** [comment]
What's the name of your package?

**Comment by benoit-pierre** [comment]
FYI, this is the regex used by pip: https://github.com/pypa/pip/blob/master/src/pip/_internal/wheel.py#L572

Way more lax indeed...

**Comment by agronholm** [comment]
Need more information. Can you point me to your project or at least give the name of the wheel name?

**Comment by OmSaran** [comment]
@agronholm 
The version name is `branch_commit`
This is the error seen with wheel version > `0.32.0`

`wheel.cli.WheelError: Bad wheel filename 'TestProject-branch_commit-py2-none-any.whl'`

The same works fine with wheel version <= 0.31.1

@benoit-pierre 
The regex used in **pip** was relaxed via https://github.com/pypa/pip/pull/4384
(refer https://github.com/pypa/pip/issues/4169)

**Comment by agronholm** [comment]
@OmSaran Can you verify that the fix works for you?

**Comment by OmSaran** [comment]
@agronholm It works, thanks for the fix!!
