### ISSUE TITLE
wheel pack --build-number=...

### ISSUE THREAD

**Issue by anntzer** [pypa/wheel#283]
One (The main?) use of wheel unpack/wheel pack would be to fix a broken wheel and repack it without invoking the build chain.  If the broken wheel has already been uploaded on PyPI, the new wheel needs to use a (higher) build number.
It would thus seem useful to be able to set this wheel number from `wheel pack --build-number=...`, rather than having to rename the wheel manually.

**Comment by anntzer** [comment]
thanks!

**Comment by anntzer** [comment]
Hum, this does not seem to work?  With wheel 0.33
```
$ cat setup.py
from setuptools import *
setup()  # filling in metadata does not help
$ python setup.py bdist_wheel
running bdist_wheel
running build
installing to build/bdist.linux-x86_64/wheel
running install
running install_egg_info
running egg_info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
Copying UNKNOWN.egg-info to build/bdist.linux-x86_64/wheel/UNKNOWN-0.0.0-py3.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/UNKNOWN-0.0.0.dist-info/WHEEL
creating 'dist/UNKNOWN-0.0.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'UNKNOWN-0.0.0.dist-info/METADATA'
adding 'UNKNOWN-0.0.0.dist-info/WHEEL'
adding 'UNKNOWN-0.0.0.dist-info/top_level.txt'
adding 'UNKNOWN-0.0.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
$ cd dist && wheel unpack UNKNOWN-0.0.0-py3-none-any.whl && wheel pack --build-number 123 UNKNOWN-0.0.0
Unpacking to: ./UNKNOWN-0.0.0...OK
Repacking wheel as ./UNKNOWN-0.0.0-py3-none-any.whl...OK
```
the build number is not applied.

**Comment by agronholm** [comment]
Indeed – my stupid mistake. I've already fixed this locally and I'll add a test to make sure it won't happen again. Expect a v0.33.1 patch release to address this very soon.

**Comment by agronholm** [comment]
Actually I'm not sure how I should go about this testing, but I've verified the fix manually so I'll just be releasing v0.33.1 now.

**Comment by agronholm** [comment]
The v0.33.1 release is now in PyPI.

**Comment by anntzer** [comment]
Thanks!
