### ISSUE TITLE
Getting http 502 error while accessing wheel-0.33.1-py2.py3-none-any.whl

### ISSUE THREAD

**Issue by vinay-is** [pypa/wheel#285]
From our local devpi server getting http 502 while accessing the latest release of wheel 0.33.1

Following is the snap shot of our local devpi server

![screen shot 2019-02-19 at 3 45 51 pm](https://user-images.githubusercontent.com/11605748/53055737-a8cb2800-345d-11e9-95b1-35a4c2cd7fa8.jpg)

So when we click the link `wheel-0.33.1-py2.py3-none-any.whl` we get following response :-
{
 "message": "error -1 getting https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl"
}

We do not getting any error while clicking 'wheel-0.33.0-py2-py3-none-any.whl' link

**Comment by agronholm** [comment]
I'm not sure what you expect me to do about your local devpi problems. Clearly downloading it works flawlessly everywhere else.
