### ISSUE TITLE
Tests not included in PyPI source distribution

### ISSUE THREAD

**Issue by ddevault** [pypa/wheel#299]

**Comment by agronholm** [comment]
Yes, this is my only project that still has a `MANIFEST.in` so I missed this detail. I wonder if there's any reason not to use setuptools_scm?

**Comment by ddevault** [comment]
Thanks!

**Comment by ddevault** [comment]
Seems `extension.c` is missing as well.

**Comment by agronholm** [comment]
> Seems extension.c is missing as well.

No, it's not? Which version are you looking at?

**Comment by ddevault** [comment]
0.33.6 source tarball. Just double checked, it's definitely not there.

**Comment by agronholm** [comment]
Yeah, it's missing from 0.33.6, but this has already been fixed in 6f1c95c1 two months ago.

**Comment by ddevault** [comment]
Ah, I didn't realize there hadn't been a new release since. Apologies.
