### ISSUE TITLE
abi3 tag missing on Windows

### ISSUE THREAD

**Issue by dholth** [pypa/wheel#300]
We tried to detect abi3 with the extension suffix, but on windows that's just .pyd. Maybe the correct check should be "is CPython and >= 3.3"? I use this in enscons to find the right tag for new wheels. https://github.com/pypa/wheel/blob/master/wheel/pep425tags.py#L139

**Comment by dholth** [comment]
I will probably switch to the new `packaging.tags` which descends from wheel's pep425tags.

**Comment by agronholm** [comment]
Not sure what you mean by the first comment, but it is not reasonably possible to detect ABI3 libraries by looking at their contents. How do you propose to differentiate between regular .pyd and those using the limited ABI?

**Comment by dholth** [comment]
It's more manual than that. The algorithm is "if the interpreter can install abi3 wheels, then compile this new extension as ABI3". https://bitbucket.org/dholth/cryptacular/src/6c9dd8646613a3a07c075bb7e71efe9f1b0a7f20/SConstruct#lines-33

The bug is that on Windows, wheel's tags say "this interpreter can't install abi3 wheels" because no abi3 tag shows up in the list.

**Comment by dholth** [comment]
Unfortunately `packaging.tags` hasn't been released yet

**Comment by dholth** [comment]
I switched to a vendored packaging.tags for enscons.

**Comment by agronholm** [comment]
But were you using the `wheel.pep425` module before?

**Comment by dholth** [comment]
Yes, it was directly importing wheel.pep425tags before. So the bug "does not list abi3 as a supported tag on Windows" is still there. It may or may not matter for bdist_wheel itself which only really needs one tag to apply to a newly built wheel, but it could be a nuisance if you are using wheel's version of pep425tags in an installer.

**Comment by agronholm** [comment]
> but it could be a nuisance if you are using wheel's version of pep425tags in an installer.

Fortunately I've stated in the README that there is no public API (yet) so anyone doing so is on their own. And even when there will be a public API, the pep425tags module will not be part of it.

Will this cause problems with packaging Windows ABI3 wheels?

**Comment by dholth** [comment]
Don't think so.
