### ISSUE TITLE
cant' make post install init work via pypi

### ISSUE THREAD

**Issue by michaelaye** [pypa/wheel#301]
I'm creating my package like so:

```
python setup.py sdist
python setup.py bdist_wheel
```
and am uploading with twine:
```
twine upload dist/*
```
In setup.py I have:
```python
from wheel.bdist_wheel import bdist_wheel
from testing_post_install_cmd import cli


class bdist_wheel_cmd(bdist_wheel):
    def run(self):
        bdist_wheel.run(self)
        cli.init()

setup(
    cmdclass={
        'install': InstallCmd,
        'egg_info': EggInfoCmd,
        'bdist_egg': bdist_egg_cmd,
        'sdist': sdist_init,
        'bdist_wheel': bdist_wheel_cmd
    },
)
```
(you can see how many install commands i'm already trying out to get this to work).

My init function still doesn't run, it does both a print-out and writing to a file, so I'm pretty sure it is not running, when install via pypi.
I have found some blogs describing this functionality a security risk, actually.
So, is this maybe not possible because of that issue?

Installing locally this all works.
If this is not possible, what is the recommended way to have a post_install initialization run ?

**Comment by jamadden** [comment]
There is no `setup.py’ involved in installing a wheel (such as distributed from PyPI). Avoiding execution of arbitrary, potentially malicious, code at install time is a design goal. https://www.python.org/dev/peps/pep-0427/ has some more info. 

While a package that wanted to run arbitrary code at install time could, currently, just avoid distributing wheels and instead only distribute source distributions that require users to run setup.py, it’s not clear to me that that would be a good long term option.

**Comment by michaelaye** [comment]
I agree, I'm helping out a package creator that currently requires this, but IMHO, it just should check if the init was yet run at run-time, and if it wasn't, call it once and be done with it. I don't see any real reason either why this would need to be run at install time.

Also, despite calling `pip install` with `-vvv` it still swallowed my print-out and my write-out file was created in the temp directory (*DOH*), so my post-install init actually worked. Closing!

**Comment by michaelaye** [comment]
actually it didn't, fooled myself with the test file being created at built-time, double-DOH. Oh, never mind.
