### ISSUE TITLE
Which files are included by default?

### ISSUE THREAD

**Issue by finswimmer** [pypa/wheel#302]
For sdist the [docu describes](https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute) which files are include in the distribution file by default.

For bdist_wheel I could find only a hint about [license files](https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file).

So my question is: Which files are included in the distribution when by default when using `python setup.py bdist_wheel`?

_I asked this last week as well on [stackoverflow](https://stackoverflow.com/q/57426655/9750706)._

**Comment by agronholm** [comment]
1. Any files produced by `python setup.py bdist` (which has nothing to do with wheel)
1. License-like files, as documented [here](https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file)
