### ISSUE TITLE
version confusion when working from github, i.e., no "dev" bumping

### ISSUE THREAD

**Issue by aixtools** [pypa/wheel#310]
Would be good, IMHO, that the version id get bumped, asin pypa/pip does:
__version__ = "19.3.dev0"

So that it is much much easier to reload the real official release.

It was quite confusing to know which version I was really using as the latest official version (e.g. 0.33.6) and the "GitHub" version strings were (read are!) identical.

Now I know how to do this on my own, and I guess the file can be ignored for pushes, but I think it would be nice if this was managed as part of the tag and release workflow.

**Comment by jamadden** [comment]
Perhaps that belongs to a higher level tool like [zest.releaser](https://zestreleaser.readthedocs.io) (which does exactly this in its [fullrelease command](https://zestreleaser.readthedocs.io/en/latest/overview.html#available-commands)).

**Comment by agronholm** [comment]
I usually use setuptools-scm for this purpose. I'm not 100% sure if this is fine for wheel but it would be preferred.

**Comment by agronholm** [comment]
@dholth Can you think of any reason why it would be a bad idea to use setuptools-scm with wheel?

**Comment by aixtools** [comment]
Discovered a new feature of github - how to see all open issues.

Anyway, as just one example, I see pypa/packaging does add devX

`./packaging/__about__.py:__version__ = "20.0.dev0"`

Just saying, it would be nice.

**Comment by agronholm** [comment]
Fixed in 9aa8480b5d2d033dbd9b634fa736d8f25150c40d.
