### ISSUE TITLE
MacOS Platform tag when MACOSX_DEPLOYMENT_TARGET is set

### ISSUE THREAD

**Issue by Czaki** [pypa/wheel#312]
On MacOs., by default Platform Tag is set to Python platform tag version https://docs.python.org/3/distutils/apiref.html#distutils.util.get_platform

But developer can set  MACOSX_DEPLOYMENT_TARGET to another version (eg, to use newer API). So can build python package which will not work on MacOs version suggested by platform tag. 

Of course it can be overwritten by `-p` flag, but I think that it should be out of box. 

Maybe some change like (https://github.com/pypa/wheel/blob/master/wheel/pep425tags.py):
```python 
def get_platform():
    """Return our platform name 'win32', 'linux_x86_64'"""
    # XXX remove distutils dependency
    result = distutils.util.get_platform()
    if result.startswith("macosx-") and "MACOSX_DEPLOYMENT_TARGET" in os.environ:
        result.rfind()
        tag = result[7:result.rfind("-")]
        parsed_tag = tuple(map(int, tag.split(".")))
        parsed_target = tuple(map(int, os.environ["MACOSX_DEPLOYMENT_TARGET"].split(".")))
        if parsed_tag < parsed_target:
            result = "macosx-" + os.environ["MACOSX_DEPLOYMENT_TARGET"] + result[result.rfind('-'):]
    result = result.replace('.', '_').replace('-', '_')
    if result == "linux_x86_64" and sys.maxsize == 2147483647:
        # pip pull request #3497
        result = "linux_i686"
    return result
```

**Comment by agronholm** [comment]
Would you like to make a PR (with test[s])?

**Comment by Czaki** [comment]
I can try.

**Comment by Czaki** [comment]
@agronholm I found other way to achieve this in other way. MacOs library header contains information about minimal system version. I wrote the code which extract this information from file. But I do not know how find information about list of files included to wheel to extract all `.dynlib` files to analyse it. Could you give me hint?

**Comment by agronholm** [comment]
Presumably you need to look at the files about to be zipped by `bdist_wheel`. The `archive_root` variable contains the base directory that you can look through.

**Comment by Czaki** [comment]
@agronholm I have created pull request #314
