### ISSUE TITLE
wheel filename without building

### ISSUE THREAD

**Issue by davidszotten** [pypa/wheel#319]
Hi,

would you accept a feature to output the filename that a wheel would use without actually building it? 

the use case is trying to figure out if the wheel is already available in our cheeseshop without spending resources compiling expensive extension

**Comment by agronholm** [comment]
This is not really possible to do in a generic fashion since there is code that looks at the generated files and determines the name from that.

**Comment by davidszotten** [comment]
oh, is it not just https://github.com/pypa/wheel/blob/master/wheel/bdist_wheel.py#L238

`archive_basename = "{}-{}-{}-{}".format(self.wheel_dist_name, impl_tag, abi_tag, plat_tag)`

**Comment by agronholm** [comment]
This is where the final file name is assembled, yes, but the issue is how to determine the parameters for that format string.

**Comment by davidszotten** [comment]
interesting. could you point me to where some of this happens?

**Comment by pfmoore** [comment]
While I can't point to code, I will give a quick example. A project that builds a C extension should have tags like `cp37-cp37m-win_amd64`, whereas a "pure Python" project would have tags like `py2.py3-none-any`. But you can't tell whether a project will build a C extension without running the build (for an extreme example, consider a `setup.py` that built an extension randomly, depending on the output of `random.choice()`)

**Comment by davidszotten** [comment]
could we e.g tell partway through the "build" but before we actually build the c-extension (which tends to be what's slow)?

**Comment by agronholm** [comment]
Not universally. The latest feature in wheel involves determining the ABI tag after the build on macOS.

**Comment by davidszotten** [comment]
ok, thanks for clarifying
