### ISSUE TITLE
Append build number to the `WHEEL` file through `wheel pack`

### ISSUE THREAD

**Issue by gpiks** [pypa/wheel#322]
When `bdist_wheel` is invoked, it appends a build number to the `WHEEL` file in `dist-info`. Do you think it makes sense to bring the behavior of `wheel pack` on par with `bdist_wheel` by appending/modifying this tag?

Currently, a package which is installed through a wheel, loses the information related to the wheel it was installed from. Extending `wheel pack` to behave similarly allows debugging of regressed wheels.

Example of what `python setup.py bdist_wheel --build-number=2` generates 
```
Wheel-Version: 1.0
Generator: bdist_wheel (0.33.6)
Root-Is-Purelib: true
Build: 2
Tag: py3-none-any
```

**Comment by agronholm** [comment]
That makes sense, yeah.

**Comment by gpiks** [comment]
I can pick it up - I have the PR ready.

**Comment by chrahunt** [comment]
Nice suggestion. :+1: [PEP 427](https://www.python.org/dev/peps/pep-0427/#file-contents) indicates that "Build" should be in `WHEEL`.
