### ISSUE TITLE
Add link to docs from repo's front page

### ISSUE THREAD

**Issue by hugovk** [pypa/wheel#324]
It's common and helpful to put a link to the docs from the repo front page. Compare wheel and pip:

![image](https://user-images.githubusercontent.com/1324225/70853457-0336e880-1eb7-11ea-92aa-7193c5b7194a.png)

![image](https://user-images.githubusercontent.com/1324225/70853470-1fd32080-1eb7-11ea-8946-dc6598757add.png)

Please could you add a link to http://wheel.readthedocs.io/?

Like this:

![image](https://user-images.githubusercontent.com/1324225/70853450-f3b79f80-1eb6-11ea-8da5-5c26286efc68.png)

And:

![image](https://user-images.githubusercontent.com/1324225/70853445-e13d6600-1eb6-11ea-830b-43d4cfe625f9.png)

Thank you!

**Comment by hugovk** [comment]
Thanks, https://github.com/pypa/wheel/commit/723ad2ab0c02ff8e8cb7c9e7e2bae40495c4da40 is good, although I meant the bit at the top that's not in Git.

**Comment by agronholm** [comment]
I figured that this change would work well for both people who only found the Github repo and the PyPI viewers who can't find the docs link on the left side.
