### ISSUE TITLE
Building wheel from read-only source on Windows gives "Access Denied" on cleanup

### ISSUE THREAD

**Issue by miuliano** [pypa/wheel#327]
When building a wheel from read-only source files (ex. files checked into Perforce), with package_data set, and on Windows, a call to `python setup.py bdist_wheel` will finish with

> error: [WinError 5] Access is denied: 'build\\bdist.win32\\wheel\\mypkg\\some_file.txt'

This is due to the read-only attribute getting passed along for package_data files during the build and install steps (see https://github.com/pypa/setuptools/issues/1424 for reference). When bdist_wheel attempts to clean up at the end of the command via 
https://github.com/pypa/wheel/blob/882650d0fd2fadd75f4ea7c5d6b62f15f81b398a/wheel/bdist_wheel.py#L270
the read-only flags will trigger an access denied exception.

According to the official docs for shutil (https://docs.python.org/3/library/shutil.html#rmtree-example), when calling `shutil.rmtree` on Windows it's necessary to have an onerror callback to deal with read-only files.

**Comment by agronholm** [comment]
Does the same happen with `setup.py bdist`?

**Comment by agronholm** [comment]
Nevermind, I didn't properly read the description.

**Comment by lvyufeng** [comment]
@agronholm it seems that the issue still exists.

**Comment by agronholm** [comment]
To verify that, could you describe what you did and what error you got?
