### ISSUE TITLE
pip 20 and pypy - changes needed to pep425tags.py

### ISSUE THREAD

**Issue by mattip** [pypa/wheel#328]
pip20 now uses packaging.tags, not pep425tags.py, but wheel does not seem to have made that change yet. This breaks building wheels for PyPy, since the semantics of the python tag changed. 
At a minimum, the pypy-specific stanza should be removed from [`get_impl_version_info`](https://github.com/pypa/wheel/blob/master/wheel/pep425tags.py#L53), so the implementation becomes a one-liner `sys.version_info[0], sys.version_info[1]`. Are there plans to transition wheel to packaging.tags?

~Is there a way to add PyPy to the testing matrix for wheel?~

See pypa/packaging#233, pypa/packaging#184, and pypa/pip#7629

**Comment by mattip** [comment]
I see there is an entry in the travis CI for pypy. Is wheel testing with pip20?

**Comment by agronholm** [comment]
I've switched wheel to use Github Actions instead of Travis, and PyPy3 is part of the matrix now. The test suite does not involve calling pip.

I will look at packaging.tags to see if wheel can use them.

**Comment by agronholm** [comment]
I've implemented the minimum required changes in `pep425tags.py`. Please test with the `pypytags` branch and report back here.

As for packaging.tags, it replace pep425tags.py, at least not completely. I would also have to decide whether it's okay to add it as a dependency or to vendor it.

**Comment by mattip** [comment]
looks good to me. I tried it out and the wheel created is now `lxml-4.5.0a0-pp36-pypy36_pp73-linux_x86_64.whl` where master created `lxml-4.5.0a0-pp373-pypy36_pp73-linux_x86_64.whl` @antocuni, does this look right: `pp36` in place of `pp373`?

**Comment by antocuni** [comment]
LGTM. I confirm that with the patched version of `wheel`, I can build a wheel and install it on PyPy

**Comment by agronholm** [comment]
I'm going to cram a couple more PRs in and then make a release. Shouldn't take more than a few days max.

**Comment by pradyunsg** [comment]
Hurrah! Thanks @agronholm! ^>^
