### ISSUE TITLE
Use regular PEP 425 interpreter tags for PyPy wheels

### ISSUE THREAD

**Issue by ncoghlan** [pypa/wheel#329]
We'd like to go back to using standard PEP 425 tags for PyPy wheels (see https://github.com/pypa/packaging/issues/233 and https://github.com/pypa/pip/issues/7629), but that entails having PyPy *build* wheels with the regular leading interpreter tag, rather than the current PyPy specific one.

I'm working on a PR to temporarily add back support for the custom tags to `pip`, but would also like to contain the problem on the `wheel` side, and will post a PR for that shortly.

**Comment by mattip** [comment]
How does this relate to issue gh-328 and the pypytags branch? I think @agronholm was going to merge that and release

**Comment by ncoghlan** [comment]
Turns out this is a duplicate of #328, but there's still a remnant of the old custom PyPy tagging in the code (it just doesn't do anything meaningful any more).

I noticed the duplication when I went to add a NEWS entry.
