### ISSUE TITLE
pep425tags.get_platform() now requires a mandatory argument

### ISSUE THREAD

**Issue by narenandu** [pypa/wheel#335]
Was that intentional to make the `pep425tags.get_platform`'s argument mandatory?

```
>>> import wheel
>>> wheel.__version__
'0.33.6'
>>> from wheel import pep425tags
>>> pep425tags.get_platform()
'win_amd64'
>>>
```

```
>>> import wheel
>>> wheel.__version__
'0.34.1'
>>> from wheel import pep425tags
>>> pep425tags.get_platform()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_platform() takes exactly 1 argument (0 given)
```

**Comment by agronholm** [comment]
Why is this filed as an issue? Wheel has no public API (as is clearly stated in the README).

**Comment by mattip** [comment]
@narenandu you may have better luck transitioning from pep425 to the [packaging](https://github.com/pypa/packaging) project which is the new way to handle things like tags and requirements, and for the specific function you are using perhaps `sysconfig.get_platform()` will suffice

**Comment by agronholm** [comment]
Yeah, what he said.

**Comment by narenandu** [comment]
Sorry for filing it as an issue, but wanted to know if the change was intentional. I will try to use `packaging` and close this issue, now that I have an alternative to look at.

**Comment by agronholm** [comment]
I did not think about it from the API perspective. I could've made it optional I guess, but it shouldn't have mattered either way.
