### ISSUE TITLE
use packaging.tags instead of pep425tags?

### ISSUE THREAD

**Issue by mattip** [pypa/wheel#345]
pip has moved to using the pypa/packaging package instead of pep425tags.py. Is there interest in moving wheel to use that as well? Should it be vendored or listed as a dependent package? I think a dependent package would be better, since it should be safe to assume a working pip exists when wheel is installed.

I am particularly interested in improving PEP 600 support for `manlinux_X_Y` wheels, see pypa/packaging#280, pypa/manylinux#494

Edit: fix link

**Comment by agronholm** [comment]
The PEP 425 support in `packaging` does not work very well for wheel: see this [comment](https://github.com/pypa/wheel/issues/328#issuecomment-577087943) of mine. Feel free to draft a PR if you feel it will improve the code though.

**Comment by pradyunsg** [comment]
@agronholm could you elaborate on how packaging.tags is not sufficient for wheel's use case?

It's worth noting that it has seen some significant API enhancements in the time for the pip 20.0 release cycle.

I'm fairly certain that @brettcannon and I would be happy to work (possibly now, possibly at a later date) with you to figure out how we can make it possible for wheel to use packaging.tags.

**Comment by mattip** [comment]
@pradyunsg xref gh-346 where I called out the methods from pep425tags that need to be replaced.

**Comment by mattip** [comment]
@agronholm I think that comment is helped by updating setuptools and pip. As for the old PyPy tags ( `pp373` rather than `pp36` ), either someone will add backward compatibility or we will continue on the path of "only use `pp36`", since that is the future.

**Comment by brettcannon** [comment]
Yep, I would be happy to help and work with @pradyunsg to fill in any identifiable gaps so the community as a whole can have a single place to manage tag-related code.

**Comment by agronholm** [comment]
> @agronholm could you elaborate on how packaging.tags is not sufficient for wheel's use case?

Seems like @mattip has already figured out what the issues are while working on the PR.
What I'm still unsure of is whether wheel can add packaging as a dependency or if it needs to vendor it.

**Comment by mattip** [comment]
Since the existing dependency on setuptools via `pkg_resources` requires a working pip, maybe a dependency on packaging is ok. That would also allow projects to update to a newer packaging without needing a new wheel release.

**Comment by agronholm** [comment]
I feel the same way, so as long as nobody comes up with any reasonable objections to that, I'm okay with adding the dependency.
