### ISSUE TITLE
wheel pack does not regenerate top_level.txt

### ISSUE THREAD

**Issue by anntzer** [pypa/wheel#353]
Running `wheel unpack`, adding a top-level module to the wheel, and repacking the wheel, does not update `top_level.txt` in dist-info.  e.g.
```
$ pip download wheel && wheel unpack *.whl && rm *.whl
$ echo 42 > wheel-0.34.2/foobar.py
$ wheel pack wheel-0.34.2
```
then examining the contents of top_level.txt in the repacked wheel shows that `foobar` was not added.

**Comment by agronholm** [comment]
This is not a use case that was considered in the implementation of `wheel pack`. Wheel does not generate `top_level.txt` so I'm not sure wheel should even attempt to rebuild it.

**Comment by anntzer** [comment]
Closing as wontfix seems fine to me (well, perhaps the docs could mention that); I'm not even sure if top_level.txt is really relevant in an eggless world (per https://setuptools.readthedocs.io/en/latest/formats.html#top-level-txt-conflict-management-metadata), just wanted to point that out.

**Comment by agronholm** [comment]
I thought that the documented description (`This is the equivalent of ``zip -r <wheel_file> <wheel_directory>`` except that it regenerates the
``RECORD`` file which contains hashes of all included files`) made it clear that it doesn't do anything else.

**Comment by anntzer** [comment]
I guess the wording made me believe not updating top_level.txt was an accidental omission.  Not a huge deal, again.
