### ISSUE TITLE
Add support for changing the wheel compression level

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#355]
Apparently wheel currently uses a rather low compression level (3) to compress the wheel zips.
Since Python 3.7+ allows us to specify the compression level, we should probably do at least some of these:

- add a `compresslevel` option to the `WheelFile` class
- add a `--compresslevel` option to the `bdist_wheel` command
- change the default compression level for `DEFLATE` compression

**Comment by malthe** [comment]
Bump?

**Comment by agronholm** [comment]
This is no longer planned in the scope of this project. If this is still wanted, it should be brought up in the wheel standard discussion on Discourse.

**Comment by eli-schwartz** [comment]
Hmm, but I can't see anywhere that the wheel standard defines what DEFLATE level to use? Changing to something like zstd or lzma would obviously require a specifications change but asking zip to spend a bit more time to pack down the contents in the same format but spend more time calculating a better dictionary is very much a "quality of life" detail that is entirely internal to implementations, if you ask me.

**Comment by agronholm** [comment]
Would you be hoping to use `wheel` to recompress a wheel file created by a build back-end, or...?
