### ISSUE TITLE
Changelog link at PyPI doesn't include all releases

### ISSUE THREAD

**Issue by michael-k** [pypa/wheel#360]
To reproduce:

- Go to https://pypi.org/project/wheel/ and see that the latest release is `0.34.2`
- Click on Changelog
  ![image](https://user-images.githubusercontent.com/152008/86336957-01a8f400-bc40-11ea-83bc-c13c36c49d55.png)
- See only release notes up to 0.33.6
  ![image](https://user-images.githubusercontent.com/152008/86337024-171e1e00-bc40-11ea-95fa-26478cc99ddb.png)
- Switch from [stable](https://wheel.readthedocs.io/en/stable/news.html) to [latest](https://wheel.readthedocs.io/en/latest/news.html) to see all release notes.

I'm not sure if best fix is to
- update stable at Read the Docs (works without a new release, but the same issue might happen with future releases) or 
- change the [link](https://github.com/pypa/wheel/blob/e8eb40e187b4ce443fc4ca4ea69c390a283f5e22/setup.cfg#L26) (should work for all future releases without overhead, but requires a new release).

Maybe both?

I'm happy to provide a PR that adjusts the link. :)

**Comment by agronholm** [comment]
The changelog from the link does contain all the releases, and I didn't make any modifications to RTD or the RTD configuration in the project.
