### ISSUE TITLE
AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'linux_aarch64')

### ISSUE THREAD

**Issue by RomanGurinovich** [pypa/wheel#367]
Experiencing this error when `pip install` _numpy_ and _cryptography_ in Docker container on Raspberry. While images built in May and June of 2020 worked well. Tried and it didn't work: 

- downgrading versions of _wheel_ and packages, 

- vice versa, upgrading _pip_, _wheel_ and packages to the very latest versions

- `pip install cryptography --no-binary cryptography`

Maybe it is an _arm64_ issue. For instance, _cryptography_ doesn't list this platform as supported https://cryptography.io/en/latest/installation/#build-on-linux

---

**Workaround**
```shell
pip install -e git+https://github.com/pyca/cryptography.git#egg=cryptography
```
---

**Details**

```shell
      File "/tmp/pip-build-env-n8ueeulb/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
        assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
    AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'linux_aarch64')
  ...
  ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
```
OS : Raspbian GNU/Linux 10 (buster)
Docker: 19.03.12
Base: python:3.8-buster

**Comment by agronholm** [comment]
Please paste the output of the following script:
```python3
from packaging import tags
from pprint import pprint

pprint(list(tags.sys_tags()))
```

**Comment by RomanGurinovich** [comment]
@agronholm, here you are 

```
pprint(list(tags.sys_tags()))
[<cp38-cp38-linux_armv7l @ 4146360008>,
 <cp38-abi3-linux_armv7l @ 4146423816>,
 <cp38-none-linux_armv7l @ 4146423784>,
 <cp37-abi3-linux_armv7l @ 4146357992>,
 <cp36-abi3-linux_armv7l @ 4146423944>,
 <cp35-abi3-linux_armv7l @ 4145553704>,
 <cp34-abi3-linux_armv7l @ 4145553768>,
 <cp33-abi3-linux_armv7l @ 4145556008>,
 <cp32-abi3-linux_armv7l @ 4145556104>,
 <py38-none-linux_armv7l @ 4145556360>,
 <py3-none-linux_armv7l @ 4145556200>,
 <py37-none-linux_armv7l @ 4145556424>,
 <py36-none-linux_armv7l @ 4145556520>,
 <py35-none-linux_armv7l @ 4145556616>,
 <py34-none-linux_armv7l @ 4145556712>,
 <py33-none-linux_armv7l @ 4145556808>,
 <py32-none-linux_armv7l @ 4145556872>,
 <py31-none-linux_armv7l @ 4145556968>,
 <py30-none-linux_armv7l @ 4145557064>,
 <py38-none-any @ 4145557160>,
 <py3-none-any @ 4145557256>,
 <py37-none-any @ 4145557416>,
 <py36-none-any @ 4145555752>,
 <py35-none-any @ 4145598600>,
 <py34-none-any @ 4145598728>,
 <py33-none-any @ 4145598856>,
 <py32-none-any @ 4145598984>,
 <py31-none-any @ 4145599112>,
 <py30-none-any @ 4145599240>]
```

**Comment by agronholm** [comment]
If you have previously built wheels around, is their platform tag also `linux_aarch64`?

**Comment by RomanGurinovich** [comment]
seems so 
```
  Building wheel for psycopg2 (setup.py): started
  Building wheel for psycopg2 (setup.py): finished with status 'done'
  Created wheel for psycopg2: filename=psycopg2-2.8.5-cp38-cp38-linux_aarch64.whl
```

**Comment by agronholm** [comment]
It looks like wheel has been using the wrong platform tag all along for this particular case (64-bit ARM running a 32-bit OS). It's the one corner case not covered by the logic in wheel's `get_platform()`.

**Comment by agronholm** [comment]
Please test the fix in the associated PR.

**Comment by RomanGurinovich** [comment]
Alex, thank you.  Unfortunately, the error persists. Exact steps:
1. On host
```shell
$ docker run -it python:3.8-buster
```

2. Getting inside container
```shell
$ docker exec -it container_id /bin/bash
```

3. Installing new _wheel_ inside the container
```shell
$ pip install https://github.com/pypa/wheel.git@b07333d62d333063e8d060fe66f6d3d26378b357
$ pip show wheel
Version: 0.35.1
```

4. Installing any package 
```shell
$ pip install cffi
    File "/usr/local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 283, in get_tag
      assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'linux_aarch64')
```

---

By the way, **both** host and container OS are reported as 64 bit, if I interpret it correctly
```
$ uname -m
aarch64
```

**Comment by agronholm** [comment]
Are you suggesting that I could reproduce this *without* ARM hardware?

**Comment by agronholm** [comment]
I remember that I have a bunch of raspberry pis at my disposal, but they're running Raspbian 9. They report `distutils.util.get_platform() == 'linux-armv7l' as expected. I'm thoroughly confused now. What do you get from that, and also `sys.maxsize`?

**Comment by RomanGurinovich** [comment]
turns out hyphen, not underscore ) Could you please PR? (Tried, insufficient permissions)
```python
>>> import distutils.util
>>> result = distutils.util.get_platform()
>>> result
'linux-aarch64'
```

**Comment by agronholm** [comment]
I didn't understand anything about your last message. Are you running a 64 bit OS or not? If you are, then it may be that `packaging.tags` has a bug.

**Comment by RomanGurinovich** [comment]
there is check `elif result == "linux_aarch64"` while `distutils.util.get_platform()` returns `linux-aarch64` with hyphen between terms

**Comment by agronholm** [comment]
Got it. Try again now please.

**Comment by RomanGurinovich** [comment]
Tried, assertion error didn't go, unfortunately. Then tried to move up from the `assert tag in supported_tags` line.
I didn't dig down to the bottom, please, treat the next experiments as a fast kludge.

1. For sure the latest change made `get_platform()` to return tag `linux-armv7l` as intended.

2. But. Somehow at the [very beginning](https://github.com/pypa/wheel/blob/0a5d541b43d35137c9109f7da48a56289867166b/src/wheel/bdist_wheel.py#L240) of the`get_tag()` function
`self.plat_name` is `linux-aarch64`
while 
`get_platform(self.bdist_dir)` is `linux-armv7l`
thus added explicit assigning to make sure that `plat_name` is set
```python
if self.plat_name and not self.plat_name.startswith("macosx"):
    self.plat_name = get_platform(self.bdist_dir)
    plat_name = self.plat_name
```

With this very strange fix _cryptography_ was built finally when running `~/cryptography# python3 setup.py bdist_wheel`. 
Does it make sense?

**Comment by mattip** [comment]
What computer are you using? Is this anyhow connected to qemu or a docker image? When you run `uname -a; python3 -c "import sys; print(sys.version); print('platform', sys.platform)"` what is the output?

**Comment by RomanGurinovich** [comment]
yes, Docker on Raspberry

On host 
```
Linux raspberrypi 4.19.75v64 #1 SMP PREEMPT Sat Oct 5 03:06:01 CEST 2019 aarch64 GNU/Linux
3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0]
platform linux
```
In container 
```
Linux 53888f3410a6 4.19.75v64 #1 SMP PREEMPT Sat Oct 5 03:06:01 CEST 2019 aarch64 GNU/Linux
3.8.5 (default, Aug  4 2020, 14:33:56) 
[GCC 8.3.0]
platform linux
```

**Comment by mattip** [comment]
It seems both inside and outside the docker you are using aarch64. What does `python3 -c "import sys, distutils.util; print(sys.maxsize); print(distutils.util.get_platform()); "`

**Comment by RomanGurinovich** [comment]
```
2147483647
linux-aarch64
```

---

by the way, noticed that similar command `pip3 install xyz` uses different _wheel_ for i.e. _numpy_ and _cffi_, even after reinstalling of the _wheel_

_numpy_
```
File "/tmp/pip-build-env-850ieytl/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
```

_cffi_
```
File "/usr/local/lib/python3.8/site-packages/wheel-0.35.1-py3.8.egg/wheel/bdist_wheel.py", line 283, in get_tag
```

Maybe that is why only some packages failed? 


I'll be back tomorrow

**Comment by agronholm** [comment]
Why is there an `.egg` of wheel in site-packages?

**Comment by agronholm** [comment]
FWIW, on Raspberry Pi 3 + Raspbian 9, `distutils.util.get_platform()` reports `linux-armv7l` as expected, at least on Python 3.7.3.

**Comment by mattip** [comment]
So you are using a 32-bit python on 64-bit arm. 

@agronholm this is on a raspberrypi 4 which supports 64 bit OSes. BTW, in the [comment](https://github.com/pypa/wheel/blob/0a5d541b43d35137c9109f7da48a56289867166b/src/wheel/bdist_wheel.py#L50) "Return a different tag for a 64-bit CPU running a 32-bit OS" it should be "Return a different tag for a 64-bit OS running a 32-bit python"

**Comment by agronholm** [comment]
Raspberry Pi 3 also has a 64-bit CPU, but Raspbian is only available in 32 bits. And yes, that would seem to be a more accurate comment.

**Comment by agronholm** [comment]
So the difference seems to be that the OS is 64-bit but the Python binary is 32-bit?

**Comment by agronholm** [comment]
If that is the case, this begs the question: why does `distutils.util.get_platform()` return an incorrect platform tag?

**Comment by mattip** [comment]
Because it parses `uname -a`, not any sysconfig variable. `packaging.tags` has a `_platform_tag()` but unfortunately it is not public. I opened an issue with packaging

**Comment by agronholm** [comment]
@RomanGurinovich since I do not currently have access to an aarch64 machine with a 64-bit OS, I need you to figure out where the `aarch64` platform name is coming from. Can you do that?

**Comment by RomanGurinovich** [comment]
let me try

**Comment by mattip** [comment]
I think this is an artifact of using a 32-bit docker image. [This stackoverflow](https://stackoverflow.com/questions/52843706/how-to-install-32-bit-docker-container) reinforces my experience: inside a 32-bit docker image running on 64-bit linux, `uname -a` will show the host kernel's information, not the docker internal information. If you really want to dig in, you can mimic this on x64 (I got the tag from [docker hub's page for linxu/386](https://hub.docker.com/layers/ubuntu/library/ubuntu/xenial-20200706/images/sha256-ea9f9fde6a023145c143db5546e03439aef953cdb120154a44fb6d6c2b6a354e?context=explore)):
```
$ export tag=sha256:ea9f9fde6a023145c143db5546e03439aef953cdb120154a44fb6d6c2b6a354e
$ sudo docker pull ubuntu:xenial@${tag}
$ sudo docker run -it ubuntu:xenial@${tag}
root@3ea890b409a3:/# echo inside the docker
inside the docker
root@3ea890b409a3:/# uname -m    
x86_64
root@3ea890b409a3:/# apt update
...
root@3ea890b409a3:/# apt install python3
...
root@3ea890b409a3:/# python3 -c"import sys; print(sys.maxsize)"
2147483647
root@3ea890b409a3:/# python3 -c"import distutils.util; print(distutils.util.get_platform())"
linux-x86_64

```

**Comment by mattip** [comment]
@RomanGurinovich what docker image are you running?

**Comment by RomanGurinovich** [comment]
@agronholm, 

It comes from linux uname(1) via Python's _os_ and then _distutils.util_ modules. In reverse, moving from _bdist_wheel.py_ >> `get_platform()`: 

`>>`  `def get_platform():` 
https://github.com/python/cpython/blob/master/Lib/distutils/util.py#L98
```
>>> os.name
'posix'
```

`>>`  `def get_host_platform()`
https://github.com/python/cpython/blob/fff3c28052e6b0750d6218e00acacd2fded4991a/Lib/distutils/util.py#L18
```
>>> "_PYTHON_HOST_PLATFORM" in os.environ
False
```
```
>>> (osname, host, release, version, machine) = os.uname()
>>> osname
'Linux'
>>> osname = osname.lower().replace('/', '')
>>> osname[:5] == "linux"
True
```
And, finally, we arrive at
```
>>> if osname[:5] == "linux":\
... "%s-%s" % (osname, machine)
'linux-aarch64'
```
Which comes from `os.uname()` relying on `uname(1)`. For instance, on the host I have
```shell
$ uname -a
Linux raspberrypi 4.19.75v64 #1 SMP PREEMPT Sat Oct 5 03:06:01 CEST 2019 aarch64 GNU/Linux
```
Does it help?

**Comment by RomanGurinovich** [comment]
@mattip, 
`python:3.8-buster`

**Comment by RomanGurinovich** [comment]
indeed, 32-bit Python inside container ... 
```
>>> sys.maxsize > 2**32
False
```
https://docs.python.org/3/library/platform.html#cross-platform

**Comment by agronholm** [comment]
@RomanGurinovich you said that even though wheel's `get_platform()` returns `linux-armv7l` as expected, `get_tag()` somehow uses `linux-aarch64`. That's what I wanted you to dig into. The only way I see that happening is if `bdist_wheel` is supplied an explicit architecture name.

**Comment by RomanGurinovich** [comment]
@agronholm , that is what frustrated me yesterday too... I didn't find the source. Maybe we can fix it with explicit `get_platform()` at the very beginning of `get_tag()` ?

**Comment by agronholm** [comment]
Is this attribute set at the beginning of the `run()` method?

**Comment by RomanGurinovich** [comment]
> Is this attribute set at the beginning of the `run()` method?

No. Everything is the same as in your PR, just added `get_platform()` to fix the issue. Search doesn't not provide `plat_name` elsewhere in repository, unless I miss something. 

Maybe it is pure Docker "ghost"? Jfyi, I've removed all containers and images to prevent caching reasons

**Comment by agronholm** [comment]
I mean, did you try logging the value of the attribute in various places around bdist_wheel to figure out where it's getting set to `linux-aarch64`?

**Comment by RomanGurinovich** [comment]
Not yet. I'll try to go through with pdb during day

**Comment by RomanGurinovich** [comment]
@agronholm , 

prior to the line `self.plat_name` is `None`
```python
    def finalize_options(self):
        ...
        self.set_undefined_options('bdist',
                                   *zip(need_options, need_options))
```
After `self.plat_name` is `'linux-aarch64'`

Which leads to 
https://github.com/python/cpython/blob/1abeda80f760134b4233608e2c288790f955b95a/Lib/distutils/dist.py#L851

**Comment by agronholm** [comment]
I wonder which command sets the value then. This is probably not unique to your case, so I could take a stab at debugging this myself.

**Comment by merwok** [comment]
I used to be deep into this distutils options code, feel free to ping me if you need any help.

**Comment by agronholm** [comment]
@merwok I have not found the time to debug this yet, but if you have any insights, they would be welcome.

**Comment by gregex5** [comment]
FYI, docker is not necessarily required for repro - I can repro on [picoreplayer](https://www.picoreplayer.org/), a distro with 64-bit kernel and 32-bit python binaries on RPi4.  I stumbled on the problem trying to pip install a project which depends on multidict, which worked fine about a month ago.

I was able to work around it by setting _PYTHON_HOST_PLATFORM=linux_armv7l

Perhaps helpful:
```
$ python3.8 -c "import platform, sysconfig; print(platform.architecture()); print (sysconfig.get_config_var('SOABI'));"
('32bit', 'ELF')
cpython-38-arm-linux-gnueabihf
$ file /usr/local/bin/python3.8
/usr/local/bin/python3.8: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, with debug_info, not stripped
```
During pip install -v I see
```
Successfully installed pip-20.2.2 setuptools-49.6.0 wheel-0.35.1
```
Other details of my system look similar to above:
```
$ uname -a
Linux myhostname 4.19.122-pcpCore_v8 #1 SMP PREEMPT Tue May 26 20:10:39 EDT 2020 aarch64 GNU/Linux
$ python3.8 -VV
Python 3.8.3 (default, Jul  9 2020, 17:59:28)
[GCC 8.1.0]
$ python3.8 -c "import sys, distutils.util; print(sys.maxsize); print(distutils.util.get_platform());"
2147483647
linux-aarch64
```
/proc/cpuinfo contains:
```
Hardware        : BCM2835
Revision        : b03111
Model           : Raspberry Pi 4 Model B Rev 1.1
```
Thanks for looking into it.

**Comment by nioncode** [comment]
> I was able to work around it by setting _PYTHON_HOST_PLATFORM=linux_armv7l

Just to clarify for others that might be struggling with where to set this: this should be set with `ENV` in the `Dockerfile` before doing the `pip install` step, e.g.:
```Dockerfile
ENV _PYTHON_HOST_PLATFORM linux_armv7l
```

This was required to build some wheels in Docker on CoreELEC, which uses a 64bit kernel with 32bit userspace as well.

**Comment by agronholm** [comment]
So where did we end up with this? I don't own the necessary hardware to test this.

**Comment by RomanGurinovich** [comment]
it builds with @nioncode instruction

**Comment by agronholm** [comment]
I now have a rpi3 in my possession so I could try to figure out if there's anything wheel can do about this.

**Comment by agronholm** [comment]
I can't reproduce this. Can you @RomanGurinovich repro it now? For me, `python:3.8-buster` downloads the aarch64 build of Python and it successfully builds aarch64 wheels.

**Comment by mattip** [comment]
I think the original issue was about building 32-bit wheels inside a docker, so it should not be building aarch64 wheels.

**Comment by agronholm** [comment]
I followed OP's instructions but could not reproduce the error. I don't know what to do.

**Comment by nioncode** [comment]
@agronholm are you running a 64bit kernel with 32bit userspace? Last time I checked (with CoreELEC and docker) this was broken for me as described in https://github.com/pypa/wheel/issues/367#issuecomment-703300287

**Comment by agronholm** [comment]
I'm running 64-bit Raspberry Pi OS beta. It has 64-bit kernel and userspace. I guess I need this specific CoreELEC distro then...?

**Comment by agronholm** [comment]
Or maybe I can repro this by running the linux/arm/v7 variant of the python docker image.

**Comment by nioncode** [comment]
If you run 64bit userspace on a 64bit kernel, everything works fine (this is more or less the default configuration similar to amd64, just on arm). Maybe you could reproduce with a 32bit raspbian, but I cannot guarantee that, since I only worked with CoreELEC before, which is a bit more work to set up I guess.

**Comment by agronholm** [comment]
Well, I tried running the armv7 variant of Python there (checked that sys.maxsize indicated 32-bit) and to my surprise it still built an aarch64 wheel, no errors. The library worked fine too.

**Comment by agronholm** [comment]
OP said the problem occurred on Raspbian 10 so I'll try with that.

**Comment by RomanGurinovich** [comment]
Alex, I'll have access to the same device next week and will try to reproduce

**Comment by agronholm** [comment]
This is what I did on Raspbian 10:
```
docker run --rm python:3.8 pip install cbor2
```
It built a `linux_armv7l` wheel as expected. I could not build a cryptography wheel due to the lack of a Rust compiler.

**Comment by agronholm** [comment]
Oh, this was Raspbian 9, not 10. Does that make a difference?

**Comment by agronholm** [comment]
To make sure, I repeated this process with Raspbian 10, and got the same results. Everything works as expected.

**Comment by agronholm** [comment]
I even downgraded wheel to v0.35.1 which was the current version at the time, and it still worked as expected.

**Comment by RomanGurinovich** [comment]
Good news, everyone,

Just setting `FROM python:3.9-buster` explicitly solves the issue. Most likely, in conjunction with the recent changes in the packages. I didn't dive deep into what else changed since that time. 

In this setup `_PYTHON_HOST_PLATFORM=linux_armv7l` is not needed anymore. 
Side note, for the current `cryptography` one might set envvar `CRYPTOGRAPHY_DONT_BUILD_RUST=1` https://github.com/pyca/cryptography/issues/5771#issuecomment-775176581.

At the same time, running previous setup failed as before.

Nothing else changed on the host or Docker
```
$ hostnamectl
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.75v64
      Architecture: arm64

$ docker --version
Docker version 19.03.12, build 48a6621

$ lscpu
Architecture:        aarch64
Model name:          Cortex-A72

$ python3
>>> platform.architecture()
('32bit', 'ELF')
```



Thus for the combination of the recent versions of the language and packages everything is fine

**Comment by agronholm** [comment]
Where did you get this OS image? This is what I have:
```
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 5.4.83-v7+
      Architecture: arm
```

**Comment by agronholm** [comment]
I installed the 64-bit beta of Raspbian 10, but even that has both 64-bit kernel and 64-bit userland.

**Comment by agronholm** [comment]
I tried piCorePlayer too but I have no clue on how to operate it.

**Comment by agronholm** [comment]
I would really welcome a clear set of repro instructions. It's been over 6 months since this was opened and I still haven't been able to repro the problem.

**Comment by mattip** [comment]
It seems like the people who reported this issue are not interested in helping @agronholm pursue a reproducer for it, so perhaps the issue should be closed.

**Comment by n8henrie** [comment]
If anyone is interested in re-opening, I've been struggling with this for a week or so and documented what is (for me) a reproducible issue [here](https://github.com/pypa/pip/issues/9980).

With current versions of `pip` and `wheel`, running on Buster with 64b kernel and 32b userland, python 3.9.4, I'm able to *build* an `aarch64` wheel (for numpy) but unable to install it.
