### ISSUE TITLE
LICENSE.txt is missing in latest pypi release

### ISSUE THREAD

**Issue by priv-kweihmann** [pypa/wheel#371]
but it was present in 0.34.2 release - please add it again

**Comment by agronholm** [comment]
This is weird. Running `python setup.py sdist` manually produces an sdist with `LICENSE.txt` included, but it's missing from the published sdist.

**Comment by agronholm** [comment]
Even using the exact same version of setuptools makes no difference. The license file is still there when I create the sdist locally.

**Comment by agronholm** [comment]
The file is definitely present because it's in the published wheel! Just not the sdist.

**Comment by priv-kweihmann** [comment]
Okay - I was just checking the sdist, as this is what I build at the moment

**Comment by agronholm** [comment]
Seems like this happened again with the latest release. If you could reproduce it locally, that would help. I cannot reproduce it here.

**Comment by priv-kweihmann** [comment]
![image](https://user-images.githubusercontent.com/46938494/100722549-04f80580-33c1-11eb-9172-a6a07a8fe36d.png)
from https://files.pythonhosted.org/packages/57/73/1911bfa69482de2a6327db4ca5eda87ae7599160018910007d6d6a1d3ada/wheel-0.36.0.tar.gz

not LICENSE.txt in the source tarball

**Comment by agronholm** [comment]
Yes, like I said. The only difference in the logs on CI is that LICENSE.txt is not copied. All the other files are. I cannot understand what could be causing this, or how to reproduce it locally.

**Comment by priv-kweihmann** [comment]
No idea to be honest - but I don't see any line matching the LICENSE.txt in https://github.com/pypa/wheel/blob/master/MANIFEST.in

**Comment by agronholm** [comment]
Yet it's always added to the sdist locally here.
