### ISSUE TITLE
How to make a numpy+mkl wheel

### ISSUE THREAD

**Issue by Qiyu8** [pypa/wheel#379]
Here is the unofficial [wheel](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy), as we can see, the `intel mkl `library were installed at the same time as this wheel is installed. I want to know how to make a wheel like this. The only difference I find is the extra `DLLs `directory compared to the wheel made by myself.

**Comment by agronholm** [comment]
I kindly ask you to post your question in the `packaging` category on discuss.python.org (https://discuss.python.org/c/packaging/14). This is a bug tracker. I personally don't know the answer to your question, but hopefully someone else on that forum will.
