### ISSUE TITLE
Provide a vendored.txt with exact versions of vendored libraries

### ISSUE THREAD

**Issue by hroncok** [pypa/wheel#392]
Wheel vendors packaging.tags. Could you please provide a vendored.txt file or similar with exact versions of vendored libraries? As a downstream packager, I'd like to be able to tell easily what version of packaging is vendored without resorting to parsing the changelog / git history. Thanks.

**Comment by agronholm** [comment]
Is there a formal standard for this somewhere?

**Comment by hroncok** [comment]
Not really, but pip, setuptools and pipenv have:

https://github.com/pypa/pip/blob/master/src/pip/_vendor/vendor.txt
https://github.com/pypa/setuptools/blob/main/pkg_resources/_vendor/vendored.txt
https://github.com/pypa/pipenv/blob/master/pipenv/vendor/vendor.txt

**Comment by pfmoore** [comment]
requirements file format is basically what pip uses.

**Comment by hroncok** [comment]
Right, for the format, it's basically anything that `pip install -r` can consume.

**Comment by hroncok** [comment]
Thanks. The hard part is to ensure the metadata stays up to date :)

**Comment by agronholm** [comment]
Not really. Starting with wheel 1.0, I expect to cease the vendoring process entirely and rely on actual dependencies.
