### ISSUE TITLE
Update RECORD when appending to wheelfile

### ISSUE THREAD

**Issue by kumaraditya303** [pypa/wheel#393]
Currently `RECORD` file only modified when the wheelfile is opened for writing. It should also update `RECORD` when appending to the zipfile.

**Comment by agronholm** [comment]
I'm not sure we can support appending in the future if some of the plans come to fruition. I'm specifically referring to the plan of packaging the payload of the wheel separately from the metadata.

**Comment by kumaraditya303** [comment]
I have a use case where I need to append binaries to the built wheel package but doing so leaves `RECORD` file not updated. I currently doing it with `zipfile.ZipFIle`

**Comment by agronholm** [comment]
If you make your case, I'll make sure it's heard when this is discussed on discuss.python.org.

**Comment by kumaraditya303** [comment]
Do you mean that I need to create a discussion on discuss.python.org ? @agronholm

**Comment by kumaraditya303** [comment]
@agronholm My use case can also be fulfilled if there was a `repack` command which would take a path to a wheel package and it will update the `RECORD` file in case of a mismatch or if the file was not found and update the wheel file.

**Comment by agronholm** [comment]
There is the `wheel pack` command but it requires you to unpack the wheel first.

**Comment by agronholm** [comment]
I meant that when the discussion related to the wheel standard is resumed, I will bring up your use case.

**Comment by kumaraditya303** [comment]
@agronholm Thanks for the confirmation.

**Comment by agronholm** [comment]
Nothing stops you from starting a conversation there on your own of course. But I recommend that you first read up on the proposal of using xz compression: https://discuss.python.org/t/improving-wheel-compression-by-nesting-data-as-a-second-zip/1747

**Comment by agronholm** [comment]
If this is ever done, it should be implemented in a public wheel API, not here.
