### ISSUE TITLE
Change Requires-Dist format to not use parentheses

### ISSUE THREAD

**Issue by uranusjr** [pypa/wheel#395]
According to the Requires-Dist section in the [active Core Metadata specification](https://packaging.python.org/specifications/core-metadata/#requires-dist-multiple-use):

> A version specifier. Tools parsing the format should accept optional parentheses around this, but tools generating it should not use parentheses.

`wheel` currently generates the version with parentheses, which is acceptable but not recommended. The format triggers bugs in the parsing tool (pypa/packaging#336). It would be perfectly reasonable to not change this due to backwards compatibility, but I want to raise the possibility since the paranthesis requirement has been removed for quite a while and may no longer be relevant.

**Comment by wimglenn** [comment]
This issue is outdated - there are no longer superfluous parens around the version specifier. However, there are still superfluous parens on conditions, probably due to some code around [here](https://github.com/pypa/wheel/blob/0.43.0/src/wheel/metadata.py#L133).
