### ISSUE TITLE
get_platform result format

### ISSUE THREAD

**Issue by rouzbeh-afrasiabi** [pypa/wheel#408]
https://github.com/pypa/wheel/blob/41b375ef33e3368f6f58c13f9649491d01c2ba5e/src/wheel/bdist_wheel.py#L50

format does not follow https://www.python.org/dev/peps/pep-0425/#id13
> The platform tag is simply distutils.util.get_platform() with all hyphens - and periods . replaced with underscore _.

Change to following:
```python
result=re.sub(r'[.-]','_',distutils.util.get_platform())
```

**Comment by agronholm** [comment]
Where is this coming from? Is wheel generating incorrect filenames?

**Comment by mattip** [comment]
Note that the result is normalized later: https://github.com/pypa/wheel/blob/41b375ef33e3368f6f58c13f9649491d01c2ba5e/src/wheel/bdist_wheel.py#L265

**Comment by agronholm** [comment]
Indeed, which is why I was asking what prompted the question. Are you by any chance attempting to use the wheel code in a Python program directly? That should not be done until wheel has a supported public API.

**Comment by rouzbeh-afrasiabi** [comment]
@agronholm Yes I was trying to use the wheel code in a python app directly.  Thanks for your responses. @agronholm and @mattip
