### ISSUE TITLE
Should the docs promote `pip wheel .` over `python setup.py bdist_wheel`?

### ISSUE THREAD

**Issue by nchammas** [pypa/wheel#424]
My knowledge of packaging conventions may be out of date, but I understand that directly invoking `setup.py` is something users should migrate away from since a) in the future it may disappear entirely and b) it has various historical quirks.

The docs for wheel [still show](https://wheel.readthedocs.io/en/latest/quickstart.html) `python setup.py bdist_wheel` as the way to build wheels. Should they be updated to call `pip wheel .` instead? Or is there some intended difference between these two commands?

**Comment by henryiii** [comment]
They should show `pipx run build --wheel` or `python -m pip install build && python -m build --wheel`, I think. They probably shouldn't show setup.py commands (https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), but then again, this is likely more focused on how things work for developers more than user facing docs. Internally, that's still the command name, even if users shouldn't be running it.

**Comment by hugovk** [comment]
Please see PR https://github.com/pypa/wheel/pull/439.
