### ISSUE TITLE
Get Dependencies from Wheels

### ISSUE THREAD

**Issue by Jillinger** [pypa/wheel#446]
Is it possible to get pip to install a module's dependencies from wheels (.whl), rather than building them from downloaded files?
Why this is important, is because I am getting errors when pip tries to build some dependencies, but these are already installed.
For example, I installed pycapnp from a .whl file, but pip tries to build it as a dependency for osmx, and the build fails.
Is there a way to direct pip to the wheels, in order to build from there? Or, why does pip fail to recognize when a dependency is already installed? 

```
Package            Version
------------------ -----------
.....
pycapnp            1.1.0
......
```

```
python -m pip wheel -w E:\python\myWhls osmx
Collecting osmx
  File was already downloaded e:\python\mywhls\osmx-0.0.4-py3-none-any.whl
Collecting lmdb~=0.98
  File was already downloaded e:\python\mywhls\lmdb-0.99-cp37-cp37m-win_amd64.whl
Collecting pycapnp~=0.6.4
  Downloading pycapnp-0.6.4.tar.gz (531 kB)
     |████████████████████████████████| 531 kB 1.1 MB/s
Building wheels for collected packages: pycapnp
  Building wheel for pycapnp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
```

```
python -m pip install osmx
Collecting osmx
  Using cached osmx-0.0.4-py3-none-any.whl (3.0 kB)
Collecting pycapnp~=0.6.4
  Using cached pycapnp-0.6.4.tar.gz (531 kB)
Requirement already satisfied: lmdb~=0.98 in c:\...\lib\site-packages (from osmx) (0.99)
Building wheels for collected packages: pycapnp
  Building wheel for pycapnp (setup.py) ... error
```

```
python -m pip install E:\python\myWhls\osmx-0.0.4-py3-none-any.whl
Processing e:\python\mywhls\osmx-0.0.4-py3-none-any.w
Collecting pycapnp~=0.6.4
  Using cached pycapnp-0.6.4.tar.gz (531 kB)
Requirement already satisfied: lmdb~=0.98 in c:\...\lib\site-packages (from osmx==0.0.4) (0.99)
Building wheels for collected packages: pycapnp
  Building wheel for pycapnp (setup.py) ... error
```

**Comment by pfmoore** [comment]
1. This is the wrong project for this, it should be reported on the pip tracker.
2. It's actually not a pip issue in any case - the line "Collecting pycapnp~=0.6.4" says that one of the projects you're installing needs pycapnp version 0.6.4, and you have 1.1.0 installed, so pip needs to remove that and install 0.6.4 - and 0.6.4 is only available on PyPI as a source distribution, so that's why pip tried to build it.

**Comment by Jillinger** [comment]
Thanks a lot.
Where can I find pip tracker?

**Comment by pfmoore** [comment]
https://github.com/pypa/pip/issues

But as I say, please don't bother reporting *this* issue there, as it's not an issue, pip is behaving correctly.

**Comment by Jillinger** [comment]
Okay. I understand. Thank you.
