### ISSUE TITLE
Error out if absolute paths used in data_files

### ISSUE THREAD

**Issue by rossburton** [pypa/wheel#448]
`data_files` in setuptools can be used to install files to arbitrary locations by using an absolute path as the target directory ([documented here](https://docs.python.org/3/distutils/setupscript.html#installing-additional-files)).

However, this is broken with wheels.  Can `bdist_wheel` somehow detect that data_files has absolute target directories and raise an error instead of the packaging silently breaking?

**Comment by agronholm** [comment]
There was extensive discussion around the topic and, IIRC, the outcome was that this was a misfeature in distutils and was not even supposed to be supported with wheels.

**Comment by agronholm** [comment]
I can look into erroring out in this case with bdist_wheel.

**Comment by agronholm** [comment]
Closing as `bdist_wheel` is now canonically a part of setuptools, and the implementation here is deprecated.
