### ISSUE TITLE
Recent release notes missing from Read the Docs site

### ISSUE THREAD

**Issue by jwodder** [pypa/wheel#471]
Despite [`docs/news.rst`](https://github.com/pypa/wheel/blob/main/docs/news.rst) covering 0.38.0, the page on the Read the Docs site at https://wheel.readthedocs.io/en/stable/news.html only goes up through 0.37.1, and [switching to the "latest" version](https://wheel.readthedocs.io/en/latest/news.html) even shows 0.37.1 as "unreleased".

**Comment by agronholm** [comment]
Good catch, thanks. This was due to the code base being reformatted with Black changing the quote marks around the version to double quotes, which the regex didn't expect.
