### ISSUE TITLE
Incorrect summary in produced wheels starting from 0.38.1

### ISSUE THREAD

**Issue by atom00** [pypa/wheel#488]
See https://pypi.org/search/?q=%3D%3Futf-8%3Fq%3F
All wheels produced after 2022/11/04 (0.38.1 release date) have incorrect summaries.

**Comment by atom00** [comment]
Just checked, actually the issue first occured in 0.38.0

**Comment by nabriis** [comment]
Similar issue for mainter list (causes PyPI to reject because of formatting)

See https://github.com/pypa/setuptools/issues/3663
for initial report.

**Comment by agronholm** [comment]
Released v0.38.4 with the fix.
