### ISSUE TITLE
Proposal: Allow macOS wheels without OS maj/min version number?

### ISSUE THREAD

**Issue by charlesnicholson** [pypa/wheel#503]
macOS platform wheel suffixes take the form `-macosx_<maj>_<min>_<arch>.whl`, for example `macosx_12_0_arm64.whl`.

Pip won't install a macOS 12 platform wheel on macOS 13, or vice versa. So, we ship both as separate wheels, despite there being no macOS-specific native code bundled inside the wheel.

Is there any appetite for enhancing bdist_wheel to make the `<maj>_<min>` part of the wheel name optional via configuration options? We'd love to just be able to specify `macosx_arm64`, for example, and promise that it will run correctly on any Apple Silicon macOS machines.

If the maj/min portion of the filename is present, pip could change to respect + require it.

**Comment by mattip** [comment]
> Pip won't install a macOS 12 platform wheel on macOS 13

Is this something new for macOS 13? Numpy provides a wheel named `numpy-1.24.1-cp310-cp310-macosx_11_0_arm64.whl` which pip happily installs on my version 12.4 macmini.

**Comment by mattip** [comment]
Please show the output of
```
python3 -c "from packaging import tags; import pprint; pprint.pprint(list(tags.sys_tags()))" |head -10
```

For me this shows that both `cp310-cp310-macosx_12_0_arm64` and `cp310-cp310-macosx_11_0_arm64` are valid tags.

**Comment by charlesnicholson** [comment]
Hi @mattip, I apologize for wasting your time. From macOS 13:

```
❯ python3.9 -m venv venv
❯ . ./venv/bin/activate
❯ python -m pip install --upgrade pip setuptools wheel build -q
❯ python -c "from packaging import tags; import pprint; pprint.pprint(list(tags.sys_tags()))" |head -10
[<cp39-cp39-macosx_13_0_arm64 @ 4343661568>,
 <cp39-cp39-macosx_13_0_universal2 @ 4344074432>,
 <cp39-cp39-macosx_12_0_arm64 @ 4344074752>,
 <cp39-cp39-macosx_12_0_universal2 @ 4344074944>,
 <cp39-cp39-macosx_11_0_arm64 @ 4344075136>,
 <cp39-cp39-macosx_11_0_universal2 @ 4344075328>,
 <cp39-cp39-macosx_10_16_universal2 @ 4344075520>,
 <cp39-cp39-macosx_10_15_universal2 @ 4344075712>,
 <cp39-cp39-macosx_10_14_universal2 @ 4344075904>,
 <cp39-cp39-macosx_10_13_universal2 @ 4343562624>,
❯ python -m pip install <MY_PACKAGE>-0.0.1-py3-none-macosx_12_0_arm64.whl
Processing <MY_PACKAGE>-0.0.1-py3-none-macosx_12_0_arm64.whl
Collecting importlib-resources
  Using cached importlib_resources-5.10.2-py3-none-any.whl (34 kB)
Collecting zipp>=3.1.0
  Using cached zipp-3.12.0-py3-none-any.whl (6.6 kB)
Installing collected packages: zipp, importlib-resources, fi.ft260
Successfully installed <MY_PACKAGE>-0.0.1 importlib-resources-5.10.2 zipp-3.12.0
```
works just fine.
