### ISSUE TITLE
Warning now produced by wheel with latest setuptools

### ISSUE THREAD

**Issue by henryiii** [pypa/wheel#507]
This now produces warnings with the latest setuptools (or errors, if warning as errors is on):

```
>   warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
E   DeprecationWarning: pkg_resources is deprecated as an API
```

https://github.com/search?q=repo%3Apypa%2Fwheel%20pkg_resources&type=code

As a stopgap, if it's safe, maybe these warnings can be caught and discarded until this is resolved?

Related to #454.

**Comment by graingert** [comment]
@agronholm woops I didn't close this with my pr message
