### ISSUE TITLE
create script wrappers on Windows by symlinking to the py3.3 launchers

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#52]
Originally reported by: **Daniel Holth (Bitbucket: [dholth](https://bitbucket.org/dholth), GitHub: [dholth](https://github.com/dholth))**

----------------------------------------

The wheel installer in Python 3.3 could produce script wrappers by symlinking the launcher .exe. Works on NTFS on Vista+.

(The wheel specification needs a "recommended installer features" section to document #! shebang fixing and things like this, and to document that the scripts folder receives special treatment.)

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/52

**Comment by agronholm** [comment]
But symlinking still requires administrator access even on those systems, does it not?

**Comment by pfmoore** [comment]
Correct

**Comment by agronholm** [comment]
So are we going to do this or not? I figured that there's a reason why setuptools/pip do not do this.

**Comment by pfmoore** [comment]
If you want my opinion, no we shouldn't. I'm not 100% sure what @dholth meant by "the wheel installer" - normally wheels get installed by pip, which has it's own approach to script wrappers. If we're talking about the ```wheel install``` command, I favour keeping that simple, and in particular avoiding getting into platform-specific complexities.

**Comment by agronholm** [comment]
This here maybe? https://github.com/pypa/wheel/blob/master/wheel/tool/__init__.py#L147

**Comment by pfmoore** [comment]
Yeah, that's the ```wheel install``` command. Like you say, pip/setuptools don't do this, so ```wheel install``` shouldn't, either.

**Comment by agronholm** [comment]
Ok, then it's settled.
