### ISSUE TITLE
Requirement ranges incompatibility with vendored packaging v23.0

### ISSUE THREAD

**Issue by DavidTProto** [pypa/wheel#520]
As part of your release notes: Updated vendored packaging to 23.0. Forgive me if I'm wrong, but I think there's a change contained in this version: https://github.com/pypa/packaging/pull/624 (_parser.py L142-146).

When you try to build using this new version using wheel==0.40.0 using `python setup.py sdist bdist_wheel`, you will get an error if your requirements.txt / setup.cfg has the package range syntax (I.e. pandas>=1.3.0,<1.5.*).

The error you will get is:

**wheel.vendored.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
pandas<1.5.*,>=1.3.0**

**Comment by agronholm** [comment]
Can you point to a repository where this is happening?

**Comment by henryiii** [comment]
FYI, that's an invalid specifier set, it should be `pandas<1.5,>=1.3.0`. The change in that PR was just to improve the error message, it will now say `"".*` suffix can only be used with `==` or `!=` operators" (but that PR not in 23.0, only an upcoming release).

**Comment by agronholm** [comment]
Yeah, it did look a bit suspicious to me.
