### ISSUE TITLE
Please allow full Python build tag syntax, including non-numeric data

### ISSUE THREAD

**Issue by gh-andre** [pypa/wheel#527]
Python defines build tag nomenclature that would work out very well for preparing builds for a release, except that many tools, like `setuptool` fail to generate build tags, even though their syntax describes that it's possible. Fortunately, `wheel` just introduced `wheel tags --build` (thank you for that), but only supports numeric build numbers, which provides limited usability.

Here's Python's description of the wheel naming nomenclature:

https://packaging.python.org/en/latest/specifications/binary-distribution-format/#file-format

, which looks like this:

    {distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl

> Optional build number. Must start with a digit. ... two-item tuple with the first item being the initial digits as an int, and the second item being the remainder of the tag as a str

Just for completeness, `setuptools` describe their syntax here. They confirmed that it's eggs that are deprecated, not build tags syntax, which simply doesn't work.

https://setuptools.pypa.io/en/latest/deprecated/commands.html#release-tagging-options

What I have been doing since I was able to update to `wheel` version 0.40.0 is building a wheel package and then using 

    wheel tags --build 123 dist\abc-4.5.6-py3-none-any.whl

, and it yields `abc-4.5.6-123-py3-none-any.whl`. This is great, but when CI runs against feature branches, there is no way to qualify builds with a branch name, so packages are being produced on a feature branch may appear more stable (i.e. greater build number) once they are downloaded by QA, but they likely to be far from it, being it a feature branch.

It would be great if `wheel` allowed the string component of the Python build tag. This way packages built in feature branches can be easily distinguished from those built on main or release branches.

NOTE: One important thing I want to mention is that build tags in this context are not intended for production package repositories, which is how many of these discussions are interpreted, but rather as a measure of a build maturity before some release, making packages that increase in quality/features with increasing build numbers. Artifactory is a good example of this - not a production repository, but a development one.

**Comment by agronholm** [comment]
Already working on it.

**Comment by gh-andre** [comment]
@agronholm @henryiii You guys are awesome. Thank you so much.
