### ISSUE TITLE
support the str component of build tags

### ISSUE THREAD

**Issue by graingert** [pypa/wheel#536]
whl build tags are defined as supporting a leading digit followed by an arbitrary str:

> Optional build number. Must start with a digit. Acts as a tie-breaker if two wheel file names are the same in all other respects (i.e. name, version, and other tags). Sort as an empty tuple if unspecified, else sort as a two-item tuple with the first item being the initial digits as an int, and the second item being the remainder of the tag as a str.

from https://packaging.python.org/en/latest/specifications/binary-distribution-format/#file-format

eg this should work:
```
wheel tags --build=1foo dist/demo_whl-1.0-py3-none-any.whl 
usage: wheeel tags [-h] [--remove] [--python-tag TAG] [--abi-tag TAG] [--platform-tag TAG] [--build NUMBER] [wheel ...]
wheeel tags: error: argument --build: invalid int value: '1foo'
```

**Comment by henryiii** [comment]
Dup of #527. Fixed but not released. Might be waiting on me (#529), but I should be able to finish that by Monday or Tuesday.

**Comment by graingert** [comment]
Thanks! I should have searched for the issue harder!
