### ISSUE TITLE
Switch to trusted publishing

### ISSUE THREAD

**Issue by woodruffw** [pypa/wheel#548]
Hi there!

I'm going through the top/critical PyPI packages to see which ones aren't using [trusted publishing](https://docs.pypi.org/trusted-publishers/) yet, and I noticed that `wheel` isn't 🙂

If you're interested, I'm happy to send a PR to tweak your publishing workflow to make it use a trusted publisher. Otherwise, please feel free to close this!

**Comment by agronholm** [comment]
Done. Feel free to check the changes.

**Comment by woodruffw** [comment]
Looks good; thanks for responding so quickly!
