### ISSUE TITLE
Parens in metadata version specifiers

### ISSUE THREAD

**Issue by jaklaassen-affirm** [pypa/wheel#551]
The [packaging spec](https://packaging.python.org/en/latest/specifications/core-metadata/#requires-dist-multiple-use) says that Requires-Dist specifiers should not have parens, but wheel add the parens [here](https://github.com/pypa/wheel/blob/main/src/wheel/metadata.py#L95).

I ran into this problem because of a super edge case installing a wheel that has exact identity (===) dependencies. Pip allows any character after an the identity specifier, which means that it also captures the closing paren and so a requirement like `requests (===1.2.3)` won't match. The identity specifiers are used for prereleases and some other special-case version specifiers.

**Comment by jaklaassen-affirm** [comment]
Agreed, and this is imo both a pip and a wheel bug. The wheel bug is arguably not because it still should work according to the spec. The pip bug just looked harder to fix given the implementation, but I didn't check whether their vendored copy of packaging was out of date. And indeed it is. Packaging has switched from a regex-only to a tokenizing parser that successfully handles the identity requirements in parens. So pip just needs to update the vendored version.

**Comment by agronholm** [comment]
I'm ready to cut a new release once the linked PR is okayed.

**Comment by agronholm** [comment]
Released.
