### ISSUE TITLE
--plat-name not used

### ISSUE THREAD

**Issue by tbsuht** [pypa/wheel#575]
Hi,

```
python3 setup.py bdist_wheel --plat-name=linux-aarch64
[...]
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/libyang/py.typed -> build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/libyang/keyed_list.py -> build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/libyang/diff.py -> build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/libyang/schema.py -> build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/libyang/xpath.py -> build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/libyang/log.py -> build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/libyang/util.py -> build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/libyang/context.py -> build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/libyang/data.py -> build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/libyang/__init__.py -> build/bdist.linux-x86_64/wheel/libyang
copying build/lib.linux-x86_64-cpython-311/_libyang.cpython-311-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
adding '_libyang.cpython-311-x86_64-linux-gnu.so'
```

why is the platform-name not used?

```
pip list
Package            Version
------------------ ---------
[...]
wheel              0.41.2
```

**Comment by tbsuht** [comment]
https://github.com/pypa/wheel/blob/dc1b9f9008d28f63258e9cb59014e9a48d2649ab/src/wheel/vendored/packaging/tags.py#L243C7-L243C7
this is coming from EXT_SUFFIX, which is basically using infos from the host machine which is building the wheel.
this seems weird to me, but I'm not really working often with python packaging ...

e.g. my wheel is called `/tmp/libyang-2.99999.99999-cp311-cp311-linux_aarch64.whl` due to `--plat-name=linux-aarch64` and I used a cross-compiler to generate binaries inside.
But the contained .so lib is called `_libyang.cpython-311-x86_64-linux-gnu.so`. This seems wrong and importing stuff will only work once I rename the installed so lib to `_libyang.cpython-311-x86_64-linux-gnu.so`.

**Comment by agronholm** [comment]
Just what are you expecting here? The wheel is named as you requested. The `wheel` package does not handle building C extensions. Are you trying to cross compile C extensions for a different architecture than the host architecture?

**Comment by tbsuht** [comment]
@agronholm 
What I did basically is (don't know whether that is a dump idea):
```
CC=/usr/bin/aarch64-linux-gnu-gcc \
LIBYANG_HEADERS=/home/user/.conan2/p/libyaeb22fb6807152/p/include \
LIBYANG_LIBRARIES=/home/user/.conan2/p/libyaeb22fb6807152/p/lib \
LIBYANG_EXTRA_CFLAGS="-I /home/user/.conan2/p/pcre215428838101c9/p/include" \
LIBYANG_EXTRA_LDFLAGS="-L /home/user/.conan2/p/libyaeb22fb6807152/p/lib" \
python3 setup.py bdist_wheel --plat-name=linux-aarch64
```

Yes, I'm creating modules for aarch64.
Where is this name coming from? `_libyang.cpython-311-x86_64-linux-gnu.so`
Is this controlled by the setup.py of the [project](https://github.com/CESNET/libyang-python/blob/master/setup.py) itself?

**Comment by agronholm** [comment]
I have not heard of anyone successfully cross compiling Python C extensions without QEmu or similar. At any rate, the problem has nothing to do with this project. Good luck!

**Comment by agronholm** [comment]
That x86-64 is coming from the architecture your Python was built for. To make wheels for another architecture, you have to run the tools on that architecture.

**Comment by henryiii** [comment]
You can force an extension using setuptools by setting `SETUPTOOLS_EXT_SUFFIX`. That won't solve the other problems, though, like linking the right libraries, getting the right compiler (even if you are using dockcross & crossenv, you'll not get the modern GCC provided by manylinux, but instead a really, really old system one that's hard to compile with), etc. There's a long discussion in several issues/PRs in cibuildwheel and the conclusion is it's _really_ hard to do this generally. Feel free to research it there. I've heard there might be a solution with the [zig](https://ziglang.org) compiler, but haven't investigated it. There's work going in writing a PEP ([720](https://peps.python.org/pep-0720), if you want to read it) to make this easier. 

I'd recommend using cibuildwheel and QEmu; slower, but works: https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation

**Comment by tbsuht** [comment]
@agronholm @henryiii 
Thanks for your help, got it working using qemu. :)
