### ISSUE TITLE
WheelFile extract does not preserve permissions

### ISSUE THREAD

**Issue by gilfree** [pypa/wheel#608]
In issue #514, the command line for `wheel unpack` was fixed to preserve executable bit for files.

https://github.com/pypa/wheel/blob/0a4f40ecf967757b43e2cdfd4b3c52b16d15614a/src/wheel/cli/unpack.py#L24

But this issue still exists when extracting files programmatically. 

For example:

```python
wheel = WheelFile(wheel_path)
wheel.extractall(temp_dir )
```

The issue is of course rooted in the same problem. As `extractall` and `extract` methods inherit from zipfile.

Maybe it will be better to override these methods for `WheelFile` and fix the permissions issue there, instead of in the `unpack` command?

Will you be open for a PR for such a change?

**Comment by agronholm** [comment]
There's the fundamental, underlying issue of the wheel standard not having explicit support for file permissions (as those are platform specific). I'm personally convinced that such support would be useful, but I think it needs to be added to the standard. I don't have the bandwidth available to drive such a change myself though.

**Comment by gilfree** [comment]
Will you be open to a PR that will apply the same fix as in unpack, to make the behavior the same?

**Comment by agronholm** [comment]
> Will you be open to a PR that will apply the same fix as in unpack, to make the behavior the same?

Yeah, sure.

**Comment by agronholm** [comment]
Closing as the `wheel.WheelFile` API is not really public or documented, and there's a proper one being (slowly) worked on. Sorry about the confusion.
