### ISSUE TITLE
bdist_wheel should be able to work with pre-computed dist-info, per PEP-517

### ISSUE THREAD

**Issue by pelson** [pypa/wheel#611]
As discussed at https://github.com/pypa/setuptools/issues/1825, PEP-517 states that a wheel building backend should be able to accept an existing dist-info directory. 

> If the build frontend has previously called ``prepare_metadata_for_build_wheel`` and depends on the wheel resulting from this call to have metadata matching this earlier call, then it should provide the path to the created ``.dist-info`` directory as the ``metadata_directory`` argument. If this argument is provided, then build_wheel MUST produce a wheel with identical metadata. The directory passed in by the build frontend MUST be identical to the directory created by prepare_metadata_for_build_wheel, including any unrecognized files it created.

Currently, ``bdist_wheel`` does not make this possible. Would it be possible to add a ``dist-info-dir`` or equivalent argument to ``bdist_wheel``?

**Comment by agronholm** [comment]
I'm closing this, as the canonical location for `bdist_wheel` is now in setuptools.

**Comment by pelson** [comment]
Thanks for following-up, and congrats on tightening the scope of the project :+1:.
I'll follow-up on ``setuptools`` (no doubt with a x-link for future readers).
