### ISSUE TITLE
`[default: ]` vs. `(default: )`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [pypa/wheel#616]
Is there a reason why default values of user options are sometimes displayed inside brackets `[]` (3 occurrences):
https://github.com/pypa/wheel/blob/376373b9690e746c36e3984808759e9c32d5e014/src/wheel/bdist_wheel.py#L200
but most often inside parentheses `()` (6 occurrences):
https://github.com/pypa/wheel/blob/376373b9690e746c36e3984808759e9c32d5e014/src/wheel/bdist_wheel.py#L195

**Comment by DimitriPapadopoulos** [comment]
See also https://github.com/pypa/distutils/issues/251, since [class `Command`](https://github.com/pypa/distutils/blob/e5b06e144d1e57e0efebbc943bf071cd22e46da8/distutils/cmd.py#L17) is defined in [distutils](https://github.com/pypa/distutils/).

**Comment by henryiii** [comment]
All this lives in setputools now. This is just a CLI tool.

**Comment by DimitriPapadopoulos** [comment]
See https://github.com/pypa/setuptools/issues/4421.
