### ISSUE TITLE
Installing wheel causes SSL errors in requests

### ISSUE THREAD

**Issue by doctorpangloss** [pypa/wheel#621]
On Windows, reproduced using a **Windows Containers on Windows** dockerfile:

## Reproduction
```
FROM mcr.microsoft.com/windows/servercore:10.0.20348.1970
RUN powershell -NoProfile -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
RUN choco install -y python --version=3.11.9
RUN pip install wheel==0.43.0
RUN pip install mediapipe
```

Eventually produces an error of the form:
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
```

This appears to be a regression, `wheel==0.42.0` does not have this issue. 

## Does not reproduce
```
FROM mcr.microsoft.com/windows/servercore:10.0.20348.1970
RUN powershell -NoProfile -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
RUN choco install -y python --version=3.11.9
RUN pip install wheel==0.42.0
RUN pip install mediapipe
```

Works correctly.

Something that changed in the last 2 weeks in other parts of the Internet infrastructure is interacting with `wheel==0.43.0` and `setuptools` (or some transient dependency) incorrectly where `wheel==0.42.0` does not.

Further investigation is coming.

**Comment by agronholm** [comment]
I have to point out that wheel 0.43.0 was published 2½ months ago, and nobody else has reported any issues. Furthermore, `mediapipe` already has wheels available, meaning the `wheel` package isn't even used. Have you checked what happens if you don't install `wheel` at all? Why are you even installing it in the first place?

**Comment by doctorpangloss** [comment]
I am still investigating the issue thanks for your patience.

**Comment by agronholm** [comment]
At any rate, you shouldn't have to install `wheel` separately. This is only necessary if you're going to use it as a command line tool.

**Comment by doctorpangloss** [comment]
I excluded `wheel` from the possible source of issues here, its misbehavior was symptomatic of the same thing that broke SSL errors. I am preparing a better bug report for the appropriate project. Thanks for your patience.
