### ISSUE TITLE
Do not log to stdout

### ISSUE THREAD

**Issue by vnmabus** [pypa/wheel#622]
In the following code you set the root logger to output to stdout:
https://github.com/pypa/wheel/blob/1e00742acc9fb33f6e71460c3844c2b66532af7f/src/wheel/_setuptools_logging.py#L12-L26

This is problematic for me, as this module is executed by one of my dependencies during a test. Setting the root logger to log to stdout means that the output of my programs are now garbage, and my tests fail.

I propose to change this package to not modify the global logging configuration, and/or provide a way to not log to stdout.

**Comment by agronholm** [comment]
This code is never run on any version of setuptools that has been released in the last several years. It's there only for backwards compatibility with old setuptools versions, and will soon be removed altogether since `bdist_wheel` has been migrated to setuptools itself now.

**Comment by vnmabus** [comment]
You are right, my setuptools version was quite old. I was able to fix my problem by updating it to the minimum setuptools version that has the module `setuptools.logging` (that is, setuptools 60.2).

Thank you for the quick answer. You can close this issue, as it is no longer relevant for me (and apparently the code will be removed anyway).
