### ISSUE TITLE
i want exact filename dm_reverb-0.8.0-cp39-cp39-manylinux2010_x86_64.whl

### ISSUE THREAD

**Issue by ethereum-cat-herders** [pypa/wheel#642]

**Comment by agronholm** [comment]
You're not supposed to try to build manylinux wheels directly. There is a proper process for creating manylinux wheels which involves the [auditwheel](https://pypi.org/project/auditwheel/) tool. Are you one of the maintainers of `dm_reverb`, or what prompted this question? Why are the [currently published binary wheels](https://pypi.org/project/dm-reverb/#files) for `dm_repair` not good enough?

**Comment by ethereum-cat-herders** [comment]
I was testing some feature for bug bounty 
so

**Comment by henryiii** [comment]
You can call cibuildwheel with `--only <identifier>`, and that will make the manylinux wheel, using the manylinux docker image and auditwheel.
