### ISSUE TITLE
test_requires not parsed to json correctly

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#75]
Originally reported by: **Daniel Holth (Bitbucket: [dholth](https://bitbucket.org/dholth), GitHub: [dholth](https://github.com/dholth))**

----------------------------------------

The versions should be parenthesized

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/75

**Comment by agronholm** [comment]
Can you expand on this because I have no clue what you're talking about?

**Comment by dholth** [comment]
This is probably related to the experimental metadata.json inside dist-info folders. I've been meaning to resolve this by not generating metadata.json by default.

**Comment by agronholm** [comment]
Closing this since metadata.json has been eliminated.
