### ISSUE TITLE
listing and uninstalling wheel packages

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#98]
Originally reported by: **zaxebo1 zaxebo1 (Bitbucket: [zaxebo1](https://bitbucket.org/zaxebo1), GitHub: [zaxebo1](https://github.com/zaxebo1))**

----------------------------------------

information of all the packages which have been installed directly from .whl format (using "wheel install <packagename>") command can be stored somewhere at single place. This information can be name of the package,version and "path where it is installed" 

and THEN LATER **wheel command** can have a new subcommand  "**wheel list**" to list them from the stored information, 

and also "**wheel uninstall <packagename>**" command to remove/uninstall the packages (which are listed)

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/98

**Comment by agronholm** [comment]
Wheel is not supposed to be an installer. Maybe even "wheel install" should be done away with. So no, I don't think we'll be adding these commands. And what's that PR you're referring to?

**Comment by dholth** [comment]
The wheel installer is a place to experiment with future revisions of the format.El 6 ago. 2017 06:05, Alex Grönholm <notifications@github.com> escribió:Wheel is not supposed to be an installer. Maybe even "wheel install" should be done away with. So no, I don't think we'll be adding these commands. And what's that PR you're referring to?

**Comment by agronholm** [comment]
Very well, but we do need to have a chat about the goals of this project when you get back from your vacation.
