### ISSUE TITLE
Cannot exclude directory

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#99]
Originally reported by: **ijl (Bitbucket: [ijl](https://bitbucket.org/ijl), GitHub: [ijl](https://github.com/ijl))**

----------------------------------------

I'm unable to exclude a directory 'test', using either MANIFEST.in or setup.py.

In MANIFEST.in, I have:
`recursive-exclude test *`

In setup.py:
`packages=find_packages(exclude=['test', ]),`

In each case, `sdist` correctly excludes the `test` directory, and `bdist_wheel` does not. The `test` directory is included in the wheel, and installed to `site-packages` at the first level, which is very undesirable.

Can you advise?

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/99

**Comment by agronholm** [comment]
Wheel does not even touch `MANIFEST.in`. Setuptools provides this information. Therefore this is not a wheel issue. Closing.

**Comment by nicobako** [comment]
I know this is an old issue, but I wanted to add something. I continued having the issues mentioned above despite trying all of the solutions. Finally, I got it working by renaming my test directory from `test` to `tests`.

I don't understand why...
